from process_csv import process_file

data = {
    "(-----) (-----) enough last night, I felt fine all day today.": {"anum": 0, "q_ja": "昨夜は十分眠ったので、今日は一日中気分が良かった。", "answer": "Having slept"},
    "(-----) your hands prevent you from (-----) a cold.": {"anum": 0, "q_ja": "手を洗うことは風邪を予防する。", "answer": "Washing catching"},
    "I have not heard him (     ) such a thing.": {"anum": 1, "q_ja": "彼がそんなことを----のを聞いたことがない。", "a_ja": ["言う", "言われること", "言うこと", "言った"]},
    "Would you mind (give) me some advice about it?": {"anum": 0, "q_ja": "それについてアドバイスをいただけませんか？", "answer": "giving"},
    "My dog is not as (     ) yours.": {"anum": 3, "q_ja": "私の犬はあなたのほど----ない。", "a_ja": ["より大きい", "最も大きい", "～と同じくらい大きい", "（誤り）"]},
    "(     ) my umbrella with me, I ran home in the rain.": {"anum": 1, "q_ja": "傘を持っていなかったので、雨の中を走って帰った。", "a_ja": ["持っていない", "決して持っていない", "持っていない", "持っていなかった"]},
    "I think (-----) strange (-----) put pineapples on a pizza.": {"anum": 0, "q_ja": "ピザにパイナップルを乗せるのは奇妙だと思う。", "answer": "it to"},
    "I was almost asleep when I heard my name (     ).": {"anum": 4, "q_ja": "名前を----とき、私はほとんど眠っていた。", "a_ja": ["呼ばれること", "呼んでいる", "呼ぶ", "呼ばれた"]},
    "The population of the U.S. is roughly (     ) large as that of Japan.": {"anum": 3, "q_ja": "アメリカの人口は日本の約----だ。", "a_ja": ["（誤り）", "（誤り）", "2.5倍", "（誤り）"]},
    "Listening to music makes me (     ) positive.": {"anum": 4, "q_ja": "音楽を聴くと前向きな----。", "a_ja": ["感じている", "感じること", "感じた", "感じる"]},
    "She continued to work (-----) (-----) lunch.": {"anum": 0, "q_ja": "彼女は昼食を食べた後も働き続けた。", "answer": "after eating"},
    "My grandfather went all the way to see the doctor, (     ) find him absent.": {"anum": 2, "q_ja": "祖父はわざわざ医者に会いに行ったが、不在だとわかっただけだった。", "a_ja": ["～するのに十分", "～しただけだった", "～するために", "～しようとして"]},
    "She grew up and became an astronaut.\nShe grew up (-----) (-----) an astronaut.": {"anum": 0, "q_ja": "彼女は成長して宇宙飛行士になった。", "answer": "to be"},
    "I tried (cook) the spaghetti with the recipe, but it tasted bad.": {"anum": 0, "q_ja": "レシピ通りにスパゲッティを料理してみたが、まずかった。", "answer": "cooking"},
    "I forgot to bring my pen. I'm wondering if you could give me something to write (     ).": {"anum": 4, "q_ja": "ペンを持ってくるのを忘れました。何か書くものを貸していただけませんか----。", "a_ja": ["～について", "～の上に", "～によって", "～で（道具）"]},
    "Bill looks (     ) healthy than he used to.": {"anum": 4, "q_ja": "ビルは以前----健康そうに見えない。", "a_ja": ["最も少ない", "より少ない（数）", "ほとんどない", "より少ない（量程度）"]},
    "I made a (-----) (-----) (-----) to China to study.": {"anum": 0, "q_ja": "私は勉強するために中国へ行く決心をした。", "answer": "decision to go"},
    "(     ) my homework assignment before the deadline, I can take a break now.": {"anum": 2, "q_ja": "締め切り前に宿題を----、今は休憩できる。", "a_ja": ["提出されている", "提出したので", "提出されて", "提出している"]},
    "(     ) of Major League baseball, I am a great fan of New York Yankees.": {"anum": 1, "q_ja": "メジャーリーグと----、私はニューヨークヤンキースの大ファンだ。", "a_ja": ["言えば", "議論すれば", "言えば", "論じれば"]},
    "The woman hated to be asked her age.\nThe woman hated (-----) (-----) her age.": {"anum": 0, "q_ja": "その女性は年齢を聞かれるのを嫌がった。", "answer": "being asked"},
    "They had to keep the (     ) through the weekend.": {"anum": 1, "q_ja": "彼らは週末中、機械を動かし続けなければならなかった。", "a_ja": ["機械を動かし続ける", "機械が動く", "機械を動かす", "動いている機械"]},
    "We tried to calm the (     ).": {"anum": 3, "q_ja": "私たちは----をなだめようとした。", "a_ja": ["赤ちゃんが泣いている", "赤ちゃんが泣いた", "泣いている赤ちゃん", "泣いた赤ちゃん"]},
    "Nancy is proud of her son (     ) the inter-high-school tennis championship last year.": {"anum": 1, "q_ja": "ナンシーは息子が昨年インターハイのテニス選手権で----を誇りに思っている。", "a_ja": ["優勝したこと", "優勝すること", "優勝する", "優勝した"]},
    "You should avoid (     ) a person after ten at night.": {"anum": 1, "q_ja": "夜10時以降に人に電話するのは避けるべきだ。", "a_ja": ["電話すること", "電話すること", "電話しないこと", "電話する"]},
    "It's important for your health (-----) (-----) (-----) too much.": {"anum": 0, "q_ja": "食べ過ぎないことが健康にとって重要だ。", "answer": "not to eat"},
    "The hotel was (     ) expensive than I thought it would be.": {"anum": 3, "q_ja": "そのホテルは私が思っていたよりも----高かった。", "a_ja": ["最も", "とても", "ずっと", "同じくらい"]},
    "The movie (-----) me (-----).": {"anum": 0, "q_ja": "その映画は私を退屈させた。", "answer": "bored me"},
    "The book is said (     ) in the eighteenth century.": {"anum": 4, "q_ja": "その本は18世紀に----と言われている。", "a_ja": ["出版される", "出版した", "出版する", "出版された"], "answer": "to have been published"},
    "The quality of the sound (     ) from those speakers shows why they are so expensive.": {"anum": 2, "q_ja": "それらのスピーカーから出る音の質は、なぜそれらがそんなに高価なのかを示している。", "a_ja": ["来る", "来ている", "来た", "来ている"]},
    "The students remained (     ) in the problem after the lesson.": {"anum": 3, "q_ja": "生徒たちは授業の後もその問題に----続けた。", "a_ja": ["興味を持たせる", "興味深い", "興味を持って", "興味"]},
    "(     ) the joke before, I didn't find it funny the second time.": {"anum": 3, "q_ja": "その冗談は以前聞いたことがあったので、2回目は面白くなかった。", "a_ja": ["聞く", "聞いた", "聞いていたので", "聞いている"]},
    "I am looking for (-----) (-----) (-----) me Spanish.": {"anum": 0, "q_ja": "私はスペイン語を教えてくれる人を探している。", "answer": "someone to teach"},
    "(     ) knowing which way to go, I had to guess.": {"anum": 2, "q_ja": "どちらの道を行けばよいかわからなかったので、推測しなければならなかった。", "a_ja": ["～として", "～ないので", "～でない限り", "～である"]},
    "Bob tried (     ) the math problem, but he failed.": {"anum": 3, "q_ja": "ボブはその数学の問題を解こうとしたが、できなかった。", "a_ja": ["解くこと", "解くことへ", "解こうとする", "解く"]},
    "The girl kept (    ).": {"anum": 2, "q_ja": "その少女は微笑み続けた。", "a_ja": ["微笑んだこと", "微笑んで", "微笑んだ", "微笑み"]},
    "The roads (     ) to the country are jammed with traffic.": {"anum": 4, "q_ja": "その国へ----道路は交通渋滞している。", "a_ja": ["続く", "続いた", "続く", "続いている"]},
    "The (     ) to the students were very difficult.": {"anum": 2, "q_ja": "生徒たちに----はとても難しかった。", "a_ja": ["与えているテスト", "出されたテスト", "出されたテスト", "与えているテスト"]},
    "(     ) with care, this machine can be used for a number of years.": {"anum": 2, "q_ja": "注意して扱えば、この機械は長年使える。", "a_ja": ["扱う", "扱われれば", "扱っている", "扱うこと"]},
    "We enjoyed (sail) all over Japan last summer.": {"anum": 0, "q_ja": "私たちは去年の夏、日本中を航海して楽しんだ。", "answer": "sailing"},
    "He wanted to compete in the Olympics and practiced very hard for it.\nHe practiced very hard (-----) (-----) in the Olympics.": {"anum": 0, "q_ja": "彼はオリンピックに出場するために、一生懸命練習した。", "answer": "to compete"},
    "It will stop (     ) this evening.": {"anum": 3, "q_ja": "今晩には----止むだろう。", "a_ja": ["雨が降ること", "雨が降ったこと", "雨が降ること", "雨が降ったこと"]},
    "I have heard this song (     ) many times on the radio.": {"anum": 1, "q_ja": "私はこの歌がラジオで何度も----のを聞いたことがある。", "a_ja": ["歌われる", "歌うこと", "歌っている", "歌う"]},
    "Scott finally decided (     ) the girl he had been dating for three years.": {"anum": 3, "q_ja": "スコットはついに3年間付き合っていた彼女と----ことに決めた。", "a_ja": ["結婚する", "結婚する", "結婚する", "結婚する"]},
    "I was (-----) (-----) (-----) study last night.": {"anum": 0, "q_ja": "昨夜は疲れすぎて勉強できなかった。", "answer": "too tired to"},
    "You want to ask Lucy why she changed her opinion.\nYou say: Lucy, what (-----) you (-----) your opinion?": {"anum": 0, "q_ja": "ルーシー、何があなたに意見を変えさせたの？", "answer": "made change"},
    "(     ) on the farm all day long, he was completely tired out.": {"anum": 1, "q_ja": "一日中農場で----、彼は完全に疲れ果てていた。", "a_ja": ["働いたので", "働いている", "働いていない", "働いた"]},
    "He doesn't like (-----) (-----) at.": {"anum": 0, "q_ja": "彼は笑われるのが好きではない。", "answer": "being laughed"},
    "She will never forget (visit) Australia last summer.": {"anum": 0, "q_ja": "彼女は去年の夏にオーストラリアを訪れたことを決して忘れないだろう。", "answer": "visiting"},
    "Mr. White (-----) his daughter (-----) (-----) a driver's license.": {"anum": 0, "q_ja": "ホワイト氏は娘に運転免許を取らせた。", "answer": "had get"},
    "(-----) a lot of homework, I asked my brother to help me.": {"anum": 0, "q_ja": "宿題がたくさんあったので、兄に手伝ってもらった。", "answer": "Having"},
    "I don't know (     ) next.": {"anum": 3, "q_ja": "次に----わからない。", "a_ja": ["何をするか", "何をする", "何をすべきか", "何についてするか"]},
    "I like (-----) (-----) video games with my friends.": {"anum": 0, "q_ja": "私は友達とテレビゲームをするのが好きだ。", "answer": "playing"},
    "I don't have time (-----) (-----).": {"anum": 0, "q_ja": "私には無駄にする時間はない。", "answer": "to waste"},
    "Please remain (     ) for a couple of minutes.": {"anum": 1, "q_ja": "数分間座ったままでいてください。", "a_ja": ["座って", "座っている", "座ること", "席に"]},
    "It was kind (     ) him to give up his seat to the old man.": {"anum": 3, "q_ja": "老人席を譲るとは----親切だった。", "a_ja": ["～によって", "～にとって", "～の（人の性質）", "～で"]},
    "She gave up (     ) part-time to finish her studies.": {"anum": 2, "q_ja": "彼女は勉強を終えるためにアルバイトを辞めた。", "a_ja": ["働くこと", "働くこと", "働くことへ", "働いた"]},
    "Saori walked (-----) with her friends in the park.": {"anum": 0, "q_ja": "サオリは公園で友達と話しながら歩いた。", "answer": "talking"},
    "I looked for something (     ).": {"anum": 3, "q_ja": "私は何か座るものを探した。", "a_ja": ["座る", "座っている", "座るための（上に）", "座る"]},
    "The band kept the audience (     ) all night.": {"anum": 1, "q_ja": "そのバンドは一晩中観客を魅了し続けた。", "a_ja": ["魅了して", "魅了する", "魅了すること", "魅了する"]},
    "Ms. Sato is afraid of (     ) a horse.": {"anum": 2, "q_ja": "佐藤さんは馬に乗るのを怖がっている。", "a_ja": ["乗る", "乗ること", "乗ること", "乗られること"]},
    "Last year's extraordinary hot summer was (     ) in twenty years.": {"anum": 3, "q_ja": "昨年の異常に暑い夏は、過去20年で----だった。", "a_ja": ["～より悪くない", "～より悪い", "断然最悪", "最も最悪"]},
    "Of the two girls (     ) over there, the taller one is my sister.": {"anum": 2, "q_ja": "あそこに----2人の少女のうち、背の高い方が私の妹だ。", "a_ja": ["立つ", "立っている", "立つ", "立った"]},
    "Stop (     ). It'll only make you miserable.": {"anum": 2, "q_ja": "----のはやめなさい。惨めになるだけだ。", "a_ja": ["心配ない", "心配すること", "心配しない", "心配すること"]},
    "(     ) Sunday, the bank was closed.": {"anum": 1, "q_ja": "日曜日だったので、銀行は閉まっていた。", "a_ja": ["日曜日で", "日曜日で", "日曜日だった", "～である"]},
    "Nikko (-----) worth (-----) several times.": {"anum": 0, "q_ja": "日光は何度か訪れる価値がある。", "answer": "is visiting"},
    "I'm sure (     ) the exam.": {"anum": 3, "q_ja": "彼女が試験に合格すると確信している。", "a_ja": ["彼女が合格する", "彼女が合格する", "彼女が合格することを", "彼女の合格"]},
    "The museum is a little (     ) far to walk from here.  You can take a bus.": {"anum": 2, "q_ja": "その博物館はここから歩くには少し遠----。バスに乗れる。", "a_ja": ["ちょうど", "あまりに", "とても", "非常に"]},
    "I heard (     ) my favorite songs.": {"anum": 4, "q_ja": "私はお気に入りの歌が演奏されるのを聞いた。", "a_ja": ["それらを演奏している", "それらが演奏している", "それらを演奏された", "それらが演奏されるのを"]},
    "He is fond (-----) (-----) the violin.": {"anum": 0, "q_ja": "彼はバイオリンを弾くのが好きだ。", "answer": "of playing"},
    "He is used (-----) (-----) for hours.": {"anum": 0, "q_ja": "彼は何時間も待つことに慣れている。", "answer": "to waiting"},
    "This bike is too big for Ted (     ).": {"anum": 3, "q_ja": "この自転車はテッドが----には大きすぎる。", "a_ja": ["乗る", "乗ること", "乗るための", "乗った"]},
    "She is proud that she was the captain of the team.\nShe is proud of (-----) (-----) the captain of the team.": {"anum": 0, "q_ja": "彼女はチームのキャプテンだったことを誇りに思っている。", "answer": "having been"},
    "I heard the result of the match. I was surprised.\nI was surprised (-----) (-----) the result of the match.": {"anum": 0, "q_ja": "試合の結果を聞いて驚いた。", "answer": "to hear"},
    "Please remember (     ) off the light before you go to bed.": {"anum": 1, "q_ja": "寝る前に電気を----のを忘れないでください。", "a_ja": ["消すこと（未来）", "消す", "消したこと（過去）", "消したこと"]},
    "(     ) from the plane, the islands were very pretty.": {"anum": 1, "q_ja": "飛行機から見ると、その島々はとてもきれいだった。", "a_ja": ["見られると", "見ると", "見ること", "見られること"]},
    "Mary can swim faster than (     ) in her class.": {"anum": 4, "q_ja": "メアリーはクラスの----よりも速く泳げる。", "a_ja": ["全ての生徒", "別の生徒", "生徒", "他のどの生徒"]},
    "I saw my (     ) on the notice board.": {"anum": 2, "q_ja": "私は掲示板に自分の----のを見た。", "a_ja": ["名前が掲示している", "名前が掲示されている", "掲示された名前", "掲示している名前"]},
    "I was impressed by Taro because he played the part of Hamlet better than (     ).": {"anum": 4, "q_ja": "太郎は----よりもハムレットの役を上手に演じたので、私は感銘を受けた。", "a_ja": ["他のどの役者", "これ以上の役者", "誰も～ない", "他のどの役者（単数）"]},
    "My mother wants (-----) (-----) abroad.": {"anum": 0, "q_ja": "母は私に留学してほしいと思っている。", "answer": "me to go"},
    "A house (     ) of straw is more easily burnt than a house of bricks.": {"anum": 4, "q_ja": "わらで----家はレンガの家よりも燃えやすい。", "a_ja": ["建てている", "建てる", "建てられている", "建てられた"]},
    "The boy opened the window, although his mother told him (     ).": {"anum": 4, "q_ja": "母親が----言ったにもかかわらず、少年は窓を開けた。", "a_ja": ["しない", "それをしない", "しない", "しないように"]},
    "I haven't got (     ) I need to help him.": {"anum": 4, "q_ja": "彼を助けるのに----を私は持っていな い。", "a_ja": ["お金と同じくらい", "お金と同じくらい", "お金と同じくらい", "同じくらいのお金を"]},
    "(     ) the topic, I said nothing in the meeting.": {"anum": 2, "q_ja": "その話題を----、私は会議で何も言わなかった。", "a_ja": ["知らないこと", "知らなかったので", "知らない", "決して知らない"]},
    "I found (     ) impossible to do the work in a day.": {"anum": 4, "q_ja": "その仕事を1日でやるのは不可能だとわかった。", "a_ja": ["何", "あれ", "どのように", "それ（形式目的語）"]},
    "That hotel is popular with people (     ) by car.": {"anum": 3, "q_ja": "そのホテルは車で----人々に人気がある。", "a_ja": ["旅行した", "旅行する", "旅行している", "旅行した"]},
    "Watch out for the (     ).": {"anum": 1, "q_ja": "----に気をつけなさい。", "a_ja": ["割れたガラス", "ガラスが割れる", "割れているガラス", "ガラスが割れた"]},
    "He left his friend (     ) in the parking lot for an hour.": {"anum": 4, "q_ja": "彼は友人を駐車場で1時間----ままにした。", "a_ja": ["待った", "待った", "待つこと", "待っている"]},
    "Many Japanese students go to Australia (-----) (-----) English.": {"anum": 0, "q_ja": "多くの日本人学生が英語を勉強するためにオーストラリアへ行く。", "answer": "to study"},
    "I couldn't finish (read) the thick book this weekend.": {"anum": 0, "q_ja": "今週末、その分厚い本を読み終えることができなかった。", "answer": "reading"},
    "(     ) from this angle, the doll looks more attractive.": {"anum": 1, "q_ja": "この角度から見ると、その人形はより魅力的に見える。", "a_ja": ["見られると", "見ると", "見ること", "見ている"]},
    "I get up (     ) earlier than John.": {"anum": 1, "q_ja": "私はジョンよりも----早く起きる。", "a_ja": ["ずっと", "より", "とても", "最も"]},
    "He is always trying (     ) his boss, but his effort doesn't seem to work well.": {"anum": 3, "q_ja": "彼はいつも上司を----しているが、その努力はうまくいっていないようだ。", "a_ja": ["怒らせない", "怒らせない", "怒らせないように", "怒らせないように"]},
    "The amount of tax I have to pay this year is twice (     ) three years ago.": {"anum": 2, "q_ja": "私が今年払わなければならない税金の額は、3年前の----。", "a_ja": ["より多い", "と同じくらい", "より少ない", "と同じくらい"]},
    "The (-----) (-----) by my grandfather is 70 years old.": {"anum": 0, "q_ja": "祖父によって建てられた家は築70年だ。", "answer": "house built"},
    "(     ) a fine day yesterday, I took my son fishing.": {"anum": 1, "q_ja": "昨日は良い----、息子を釣りに連れて行った。", "a_ja": ["天気だったので", "天気だったので", "天気", "天気だった"]},
    "(-----) (-----) her before, I found Mary quickly at the party.": {"anum": 0, "q_ja": "以前彼女に会ったことがあったので、パーティーですぐにメアリーを見つけた。", "answer": "Having met"},
    "I found (-----) difficult (-----) (-----) German.": {"anum": 0, "q_ja": "ドイツ語を学ぶのは難しいとわかった。", "answer": "it to learn"},
    "Did you read the article about the old (     ) at the farm?": {"anum": 2, "q_ja": "農場で見つかった----についての記事を読みましたか？", "a_ja": ["見つかった硬貨", "見つかった硬貨", "硬貨が見つかる", "硬貨を見つける"]},
    "Tom is (     ) taller than Jim.": {"anum": 4, "q_ja": "トムはジムよりも----背が高い。", "a_ja": ["より", "とても", "最も", "ずっと"]},
    "Don't forget (     ) me his photo tomorrow.": {"anum": 4, "q_ja": "明日、彼の写真を私に----のを忘れないで。", "a_ja": ["持ってきた", "持ってくること", "持ってきたこと", "持ってくること（未来）"]},
    "Her idea sounds (-----).": {"anum": 0, "q_ja": "彼女のアイデアは面白そうだ。", "answer": "interesting"},
    "Come here as soon as you (     ).": {"anum": 4, "q_ja": "----だけ早くここに来なさい。", "a_ja": ["能力がある", "できる", "可能", "できる"]},
    "Diana is (     ) runner in her class, but her brother runs much faster.": {"anum": 4, "q_ja": "ダイアナはクラスで----ランナーだが、彼女の兄はずっと速く走る。", "a_ja": ["より速い", "最も速い", "一番速い", "一番速い"]},
    "My mother (-----) me (-----) (-----) my room at once.": {"anum": 0, "q_ja": "母は私にすぐに部屋を掃除させた。", "answer": "made clean"},
    "It's not so easy (-----) (-----) new friends.": {"anum": 0, "q_ja": "新しい友達を作るのはそれほど簡単ではない。", "answer": "to make"},
    "The tall man (     ) near the door is my father.": {"anum": 4, "q_ja": "ドアの近くに----背の高い男性は私の父だ。", "a_ja": ["立つ", "立った", "立っている", "立っている"]},
    "Tomoko is accustomed (     ) till late at night.": {"anum": 2, "q_ja": "トモコは夜遅くまで----慣れている。", "a_ja": ["働く", "働くことに", "働くこと", "働くこと"]},
    "Arizona has (     ) Native American population in the United States.": {"anum": 1, "q_ja": "アリゾナ州は米国で----ネイティブアメリカンの人口を抱えている。", "a_ja": ["3番目に大きい", "3番目に大きい", "最も大きい3番目", "最も大きいの3分の1"]},
    "I have two sisters.  Emily is (     ) of the two.": {"anum": 4, "q_ja": "私には2人の姉妹がいる。エミリーは2人のうちで----。", "a_ja": ["一番若い", "より若い", "一番若い", "より若い方"]},
    "I'm proud of (     ) the speech contest.": {"anum": 3, "q_ja": "私はスピーチコンテストで----ことを誇りに思っている。", "a_ja": ["私が勝った", "私が勝ったこと", "勝ったこと", "私が勝った"]},
    "It's a shame that none of the people (     ) for the job were accepted.": {"anum": 3, "q_ja": "その仕事に----人の誰も採用されなかったのは残念だ。", "a_ja": ["応募する", "応募", "応募している", "応募した"]},
    "This is the (     ) largest library in our city.": {"anum": 3, "q_ja": "これは私たちの市で----大きい図書館だ。", "a_ja": ["最も", "より", "2番目に", "2倍"]},
    "The schedule stayed (     ) in spite of the accident.": {"anum": 1, "q_ja": "事故にもかかわらず、スケジュールは----。", "a_ja": ["変更されない", "変更しない", "変更しない", "変更していない"]},
    "We saw her (     ) into the theater with her boyfriend.": {"anum": 3, "q_ja": "私たちは彼女が彼氏と劇場に----のを見た。", "a_ja": ["行った", "行く", "行く", "行った"]},
    "I (     ) someone touch me on the shoulder.": {"anum": 3, "q_ja": "私は誰かが私の肩に触れるのを----。", "a_ja": ["持っていた", "得た", "感じた", "見た"]},
    "He must be foolish (-----) (-----) such a story.": {"anum": 0, "q_ja": "そんな話を信じるなんて、彼は愚かに違いない。", "answer": "to believe"},
    "She had to go out again because she had forgotten (     ) some milk.": {"anum": 3, "q_ja": "彼女は牛乳を----のを忘れていたので、また出かけなければならなかった。", "a_ja": ["買うこと", "買ったこと", "買うこと（未来）", "買うこと"]},
    "The weather (     ), we had to cancel our trip to the mountains.": {"anum": 3, "q_ja": "天気が----、私たちは山への旅行を中止しなければならなかった。", "a_ja": ["悪いだろう", "悪化するだろう", "悪かったので", "悪かった"]},
    "The (-----) (-----) next to Yuki are Kana and Beth.": {"anum": 0, "q_ja": "ユキの隣に座っている少女たちはカナとベスだ。", "answer": "girls sitting"},
    "She ran fast (     ) a bus.": {"anum": 4, "q_ja": "彼女はバスに----速く走った。", "a_ja": ["～するために", "～するために", "～するために", "～するために"]},
    "I asked my uncle (-----) (-----) (-----) the piano.": {"anum": 0, "q_ja": "私は叔父にピアノの弾き方を教えてくれるように頼んだ。", "answer": "to teach me"},
    "Could you show me (     ) to use the new computer?": {"anum": 4, "q_ja": "新しいコンピュータの----を教えてくれませんか？", "a_ja": ["何", "あれ", "どれ", "どのように"]},
    "This bridge is 10 meters long.  That bridge is 5 meters long.  This bridge is (     ) that one.": {"anum": 2, "q_ja": "この橋は長さ10メートル、あの橋は5メートルだ。この橋はあの橋の----だ。", "a_ja": ["2番目に長い", "2倍の長さ", "2番目に長い", "2倍長い"]},
    "Some of your (     ) items were found this morning.": {"anum": 4, "q_ja": "あなたの----品物のいくつかが今朝見つかりました。", "a_ja": ["失っている", "損失", "失う", "失われた"]},
    "This question is (     ) than that one.": {"anum": 3, "q_ja": "この質問はあの質問よりも----。", "a_ja": ["少し難しい", "まだ難しい", "より難しくない", "ずっと難しい"]},
    "I hurried to the bank (     ) find it closed.": {"anum": 3, "q_ja": "銀行へ急いだが、閉まっていた----。", "a_ja": ["～するために", "～するために", "～しただけだった", "～するために"]},
    "I don't know (-----) (-----) (-----) for lunch.": {"anum": 0, "q_ja": "昼食に何を食べるべきかわからない。", "answer": "what to eat"},
    "Please don't forget (     ) this letter on your way home today.": {"anum": 1, "q_ja": "今日家に帰る 途中でこの手紙を----のを忘れないでください。", "a_ja": ["投函すること（未来）", "投函する", "投函したこと", "投函されること"]},
    "(     ), Naomi remained silent.": {"anum": 2, "q_ja": "----、ナオミは黙っていた 。", "a_ja": ["何と言うべきか知らず", "何と言うべきか知らなかったので", "何と言うべきか知らず", "何と言うべきか知らず"]},
    "A good teacher allows students (     ) some things for themselves.": {"anum": 4, "q_ja": "良い教師は生徒に自分で何かを----。", "a_ja": ["発見すること", "発見する", "発見された", "発見すること"]},
    "The man often leaves the door (     ) all day.": {"anum": 4, "q_ja": "その男は一日中ドアを----ままにしておくことがよくある。", "a_ja": ["鍵を開ける", "鍵を開けている", "鍵を開けること", "鍵のかかっていない"]},
    "You will find (     ) finish the job in a day.": {"anum": 4, "q_ja": "その仕事を1日で終えるのは----とわかるだろう。", "a_ja": ["難しい", "難しい", "難しい", "それが難しいと"]},
    "(-----) alone in the room, the boy began to play video games.": {"anum": 0, "q_ja": "部屋に一人残されて、少年はテレビゲームをし始めた。", "answer": "Left"},
    "Thomas didn't (     ) his daughter go out after dinner.": {"anum": 3, "q_ja": "トーマスは夕食後に娘 が外出するのを----。", "a_ja": ["望む", "許す", "させる", "助言する"]},
    "Mr. Green is one of the (     ) in our country.": {"anum": 2, "q_ja": "グリーン氏は我が国で----の一人だ。", "a_ja": ["より偉大な科学者", "最も偉大な科学者たち", "より偉大な科学者たち", "最も偉大な科学者"]},
    "I'm very happy (-----) (-----) from you.": {"anum": 0, "q_ja": "あなたから便りをもらってとても嬉しい。", "answer": "to hear"},
    "(-----) by my sister, I finished the report by the deadline.": {"anum": 0, "q_ja": "姉に手伝ってもらって、私は締め切りまでにレポートを終わらせた。", "answer": "Helped"},
    "The boys insisted (     ) back to the amusement park.": {"anum": 3, "q_ja": "少年たちは遊園地に----と言い張った。", "a_ja": ["行く", "行くこと", "行くこと", "行くこと"]},
    "Have you finished (     ) your book report?": {"anum": 1, "q_ja": "読書感想文を----終えましたか？", "a_ja": ["書くこと", "書くこと", "書く", "書いた"]},
    "He spent all afternoon (-----) for the exams.": {"anum": 0, "q_ja": "彼は午後ずっと試験勉強をして過ごした。", "answer": "studying"},
    "I saw Mike (    ) the ball.": {"anum": 2, "q_ja": "私はマイクがボールを----のを見た。", "a_ja": ["蹴られた", "蹴る", "蹴ること", "蹴られた"]},
    "It was careless (     ) me to forget my textbook in your room.": {"anum": 3, "q_ja": "あなたの部屋に教科書を忘れるなんて、私は不注意だった。", "a_ja": ["～にとって", "～で", "～の（人の性質）", "～へ"]},
    "(     ) down the street, I saw an old friend of mine.": {"anum": 1, "q_ja": "通りを----、旧友に会った。", "a_ja": ["歩いていると", "歩くこと", "歩いた", "歩いたので"]},
    "It's impossible to make her (     ) the theory.": {"anum": 3, "q_ja": "彼女にその理論を----のは不可能だ。", "a_ja": ["理解すること", "理解している", "理解する", "理解された"]},
    "(     ) way to go, I had to guess.": {"anum": 2, "q_ja": "どちらの道を行けばよいか----ので 、推測しなければならなかった。", "a_ja": ["何を知らない", "どちらを知らなかったので", "何を知っている", "どちらを知らない"]},
    "The boy is used (     ) his own breakfast.": {"anum": 1, "q_ja": "その少年は自分の朝食を----慣れている。", "a_ja": ["作ることに", "作る", "作ること", "作る"]},
    "I'm sure of (     ) the exam.": {"anum": 1, "q_ja": "私は彼が試験に----と確信している（文脈的にhim/herが抜けているが、passingが正解）。", "a_ja": ["合格すること", "合格した", "合格すること", "合格"]},
    "The boy (     ) in the accident was taken to the hospital.": {"anum": 3, "q_ja": "事故で----少年は病院に運ばれた。", "a_ja": ["怪我をする", "怪我をしている", "怪我をした", "怪我をした"]},
    "I have a lot of homework (-----) (-----).": {"anum": 0, "q_ja": "私にはやるべき宿題がたくさんある。", "answer": "to do"},
    "The higher you climb up the mountain, (     ) it will be.": {"anum": 4, "q_ja": "山を高く登れば登るほど、----なる。", "a_ja": ["寒い", "一番寒い", "より寒い", "ますます寒く"]},
    "There are more private schools in Tokyo than in (     ) other city in Japan.": {"anum": 1, "q_ja": "東京には日本の他の----都市よりも多くの私立学校がある。", "a_ja": ["どの", "多くの", "いくつかの", "ない"]},
    "The (     ) you are, the more you need to pay attention to your health.": {"anum": 2, "q_ja": "----、健康に注意を払う必要がある。", "a_ja": ["最も忙しい", "より忙しい", "忙しい", "忙しくない"]},
    "A knife and fork were not always tools (     ) in Asia.": {"anum": 1, "q_ja": "ナイフとフォークはア ジアでは必ずしも----道具ではなかった。", "a_ja": ["食事するための", "食事している", "食事する", "食事のための"]},
    "(     ) well the night before, I felt much better.": {"anum": 1, "q_ja": "前の晩によく----、気分はずっと良かった。", "a_ja": ["眠ったので", "眠ること", "眠ったこと", "眠った"]},
    "Mary needs someone (     ) care of her baby.": {"anum": 1, "q_ja": "メアリーは赤ちゃんの----人を必要としている。", "a_ja": ["世話をする", "世話をしている", "世話をされる", "世話をする人"]},
    "I like the blue coat better.  I think it's much prettier, but it costs (     ) the brown coat.": {"anum": 2, "q_ja": "私は青いコートの方が好きだ。ずっと可愛いと思うが、茶色のコートの----の値段がする。", "a_ja": ["2倍", "2倍", "2倍以上", "2倍以上"]},
    "My brother explained (     ) the Internet.": {"anum": 3, "q_ja": "兄はインターネットへの----を説明してくれた。", "a_ja": ["私にアクセスする", "アクセスする", "アクセスする方法", "アクセスするために"]},
    "The old man is said (     ) a great athlete when he was young.": {"anum": 1, "q_ja": "その老人は若い 頃、偉大なスポーツ選手----と言われている。", "a_ja": ["～だったと", "～である", "～だった", "～である"]},
    "He got his (     ).": {"anum": 4, "q_ja": "彼は----。", "a_ja": ["新しい盗む自転車", "新しい自転車盗む", "新しい盗まれた自転車", "新しい自転車を盗まれた"]},
    "She didn't check if she had a clean (     ) shirt.": {"anum": 4, "q_ja": "彼女は----きれいなシャツがあるかどうか確認しなかった。", "a_ja": ["アイロンをかけられている", "アイロンをかけた", "アイロン", "アイロンのかかった"]},
    "Because the room was terribly noisy, I couldn't make myself (     ).": {"anum": 1, "q_ja": "部屋がひどく騒がしかったので、私の声は----なかった（聞いてもらえなかった）。", "a_ja": ["聞かれる", "聞く", "聞いている", "聞く"]},
    "Please let me (     ) when you're moving.": {"anum": 2, "q_ja": "引っ越すときは----ください。", "a_ja": ["知られている", "知る（知らせる）", "知っている", "知ること"]},
    "The scholars stood (     ) at the sight.": {"anum": 4, "q_ja": "学者たちはその光景に----立っていた。", "a_ja": ["興奮させる", "興奮すること", "興奮させる", "興奮して"]},
    "We heard (     ) in the room.": {"anum": 1, "q_ja": "私たちは部屋で----のを聞いた。", "a_ja": ["誰かが話している", "話された誰か", "話している誰か", "誰かが話した"]},
    "That cafe is a popular place (     ) take a rest for hikers.": {"anum": 1, "q_ja": "あのカフェはハイ カーが----人気のある場所だ。", "a_ja": ["～するための", "～ということ", "～する場所", "～だけれども"]},
    "You should teach your children (     ) to swim.": {"anum": 3, "q_ja": "あなたは子供たちに----を教 えるべきだ。", "a_ja": ["何", "誰", "どのように", "なぜ"]},
    "I finished (     ) my homework before dinner.": {"anum": 4, "q_ja": "私は夕食前に宿題を終えた。", "a_ja": ["すること", "する", "した", "すること"]},
    "Can you see the (    )?": {"anum": 4, "q_ja": "----が見えますか？", "a_ja": ["走る馬", "馬が走っている", "馬が走る", "走っている馬"]},
    "I sometimes heard my father (     ) a song in the bathroom late at night.": {"anum": 4, "q_ja": "私は時々、父が夜遅くに風呂場で歌を----のを聞いた。", "a_ja": ["歌ったこと", "歌うこと", "歌われている", "歌っている"]},
    "John asked me (     ) him with his homework.": {"anum": 4, "q_ja": "ジョンは私に宿題を----ように頼んだ。", "a_ja": ["手伝う", "手伝っている", "手助け", "手伝うように"]},
    "The boy had the hole in his jeans (     ) yesterday.": {"anum": 2, "q_ja": "その少年は昨日ジーンズの穴を----。", "a_ja": ["直す", "直してもらった", "直すこと", "直している"]},
    "She is (     ) going to Okinawa next month.": {"anum": 4, "q_ja": "彼女は来月沖縄に行くのを楽しみにしている。", "a_ja": ["～しようとしている", "～を探している", "～の世話をしている", "～を楽しみにしている"]},
    "Amanda is (     ) of the two secretaries in the office.": {"anum": 3, "q_ja": "アマンダはオフィスの2人の秘書のうち、----方だ。", "a_ja": ["最も信頼できる", "信頼できる", "より信頼できる", "より信頼できる"]},
    "I'm sorry we have kept you (     ) so long.": {"anum": 3, "q_ja": "長い間----申し訳ありませ ん。", "a_ja": ["待つこと", "待った", "待たせて", "待つ"]},
    "I chose this red jacket because the blue jacket was (     ) this one.": {"anum": 1, "q_ja": "青いジ ャケットは----ので、私はこの赤いジャケットを選んだ。", "a_ja": ["これほど良くない", "良くない", "同じくらい良い", "同じくらい良い"]},
    "My camera is (     ) better than yours.": {"anum": 4, "q_ja": "私のカメラはあなたのよりも----良い。", "a_ja": ["より", "とても", "さらに", "ずっと"]},
    "Doesn't Betty's mother complain about (     ) every night?": {"anum": 3, "q_ja": "ベティの母親は、----について文句を言いませんか？", "a_ja": ["あなたが電話すること", "あなたが電話する", "あなたが電話すること", "あなたが電話すること"]},
    "I remember (     ) the famous painter at that party.": {"anum": 1, "q_ja": "私はそのパーティーで有名な画家に----を覚えている。", "a_ja": ["会ったこと", "会うこと", "会われること", "会うことへ"]},
    "My sister is cleaning the room (     ) her favorite song.": {"anum": 2, "q_ja": "私の姉はお気に入りの歌を----部屋を掃除している。", "a_ja": ["歌われた", "歌いながら", "歌った", "歌う"]},
    "Our library has many books in English.  You should read as (     ) as possible.": {"anum": 4, "q_ja": "私たちの図書館には英語の本がたくさんある。できるだけ----読むべきだ。", "a_ja": ["それらの多く", "それらの多く（不可算）", "それらの多く（不可算）", "それらの多く（可算）"]},
    "He is (-----) (-----) (-----) the race.": {"anum": 0, "q_ja": "彼はそのレースに勝つと確信している。", "answer": "sure of winning"},
    "Keep the water (     ) until it gets hot.": {"anum": 2, "q_ja": "お湯になるまで水を----しておきなさい。", "a_ja": ["出しておくこと", "出しっぱなしに", "出すこと", "出す"]},
    "She sat (-----) by her grandchildren.": {"anum": 0, "q_ja": "彼女は孫たちに囲まれて座っていた。", "answer": "surrounded"},
    "Don't forget (     ) the window before going to bed.": {"anum": 2, "q_ja": "寝る前に窓を----のを忘 れないで。", "a_ja": ["閉められる", "閉めること", "閉めている", "閉める"]},
    "(-----) in the sea, I saw a big ship in the distance.": {"anum": 0, "q_ja": "海で泳いでいると、遠くに大きな船が見えた。", "answer": "Swimming"},
    "The crowd was surprised to see that a seven-year-old boy was able to swim as (     ) the teenagers.": {"anum": 4, "q_ja": "群衆は、7歳の少年がティーンエイジャーと----泳げるのを見て驚いた。", "a_ja": ["より速く", "より速く", "まだ速く", "同じくらい速く"]},
    "(     ) late without an appointment, I had to wait to see the doctor.": {"anum": 1, "q_ja": "予約なしで遅れて----、医者に診てもらうために待たなければならなかった。", "a_ja": ["到着したので", "到着した", "到着した", "到着している"]},
    "Kate (     ) to go to the concert with Tommy.": {"anum": 1, "q_ja": "ケイトはトミーとコンサートに行くのを----。", "a_ja": ["ためらった", "あきらめた", "否定した", "楽しんだ"]},
    "The game looked (     ), so he didn't join it.": {"anum": 2, "q_ja": "そのゲームは----に見えたの で、彼は参加しなかった。", "a_ja": ["退屈した", "退屈な", "退屈させる", "退屈させること"]},
    "I don't mind leaving at six o'clock: (     ) up early.": {"anum": 3, "q_ja": "6時に出発するのは構わない。早起きには慣れている。", "a_ja": ["早起きに慣れている", "早起きに慣れていた", "早起きに慣れている", "早起きに慣れていた"]},
    "He stopped (     ) for his health.": {"anum": 1, "q_ja": "彼は健康のために----をやめた。", "a_ja": ["喫煙", "吸うために", "吸うことへ", "吸われること"]},
    "Can I get (-----) (-----) (-----)?": {"anum": 0, "q_ja": "何か書くものを貸してもらえますか？", "answer": "something to write"},
    "The colorful cell phones (     ) at the store are popular amoung young people.": {"anum": 2, "q_ja": "その店で----カラフルな携帯電話は若者の間で人気がある。", "a_ja": ["売る", "売られている", "売ったこと", "売られている"]},
    "She is said (     ) in France when she was young.": {"anum": 3, "q_ja": "彼女は若い頃フランスに----と言われている。", "a_ja": ["いる", "いること", "いたこと", "いた"]},
    "They looked (-----) at the result of the game.": {"anum": 0, "q_ja": "彼らは試合の結果にがっかりしたように見えた。", "answer": "disappointed"},
    "This winter is (     ) colder than last winter.": {"anum": 2, "q_ja": "今年の冬は去年の冬よりも----寒い。", "a_ja": ["そのような", "ずっと", "とても", "あまりに"]},
    "I felt (     ) when I made such a simple mistake.": {"anum": 3, "q_ja": "そんな単純な間違いをして----。", "a_ja": ["恥ずかしくさせる", "恥ずかしい", "恥ずかしい思いをした", "恥ずかしくさせられる"]},
    "She got up at five (-----) (-----) a ticket for the concert.": {"anum": 0, "q_ja": "彼女はコンサートのチケットを買うために5時に起きた。", "answer": "to buy"},
    "This book is (-----) (-----) for children (-----) (-----).": {"anum": 0, "q_ja": "この本は子供が読むには難しすぎる。", "answer": "too difficult to read"},
    "She grew up (-----) (-----) a famous writer.": {"anum": 0, "q_ja": "彼女は成長して有名な作家になった。", "answer": "to be"},
    "Lucy has three younger sisters.  She is used (     ) care of children.": {"anum": 2, "q_ja": "ルーシーには3人の妹がいる。彼女は子供の----慣れている。", "a_ja": ["世話をする", "世話をすることに", "世話をするために", "世話をされる"]},
    "You should try (-----) (-----) (-----) late again.": {"anum": 0, "q_ja": "二度と遅れないように努めるべきだ。", "answer": "not to be"},
    "The typhoon hit the city, (     ) great damage.": {"anum": 4, "q_ja": "台風がその都市を襲い、大きな 被害を----。", "a_ja": ["した", "引き起こされる", "引き起こした", "引き起こして"]},
    "She denied that she had had a date with Jim.\nShe denied (-----) (-----) a date with Jim.": {"anum": 0, "q_ja": "彼女はジムとデートしたことを否定した。", "answer": "having had"},
    "I'm going to study harder (     ) pass my exam in July.": {"anum": 1, "q_ja": "7月の試験に合格する----、もっと一生懸命勉強するつもりだ。", "a_ja": ["～するために", "～するために", "～するために", "～するために"]},
    "It's no use (     ) with her - she won't listen.": {"anum": 4, "q_ja": "彼女と----も無駄だ、彼女 は聞こうとしない。", "a_ja": ["議論したこと", "議論することへ", "議論する", "議論すること"]},
    "His speech was (-----) (-----) (-----).": {"anum": 0, "q_ja": "彼のスピーチは聞いていて退屈だった。", "answer": "boring to hear"},
    "(     ) by his parents, Takashi finally decided to go to Canada.": {"anum": 2, "q_ja": "両親に----、タカシはついにカナダに行くことを決めた。", "a_ja": ["励まして", "励まされて", "励ました", "励ますために"]},
    "(-----) is dangerous (-----) (-----) in the river.": {"anum": 0, "q_ja": "その川で泳ぐのは危険だ。", "answer": "It to swim"},
    "(     ) what their teacher said, the students were satisfied.": {"anum": 1, "q_ja": "先生の言ったことを----、生徒たちは満足した。", "a_ja": ["理解して", "理解すること", "理解すべき", "理解した"]},
    "Ms. Jones went to her office (     ) that the windows were broken.": {"anum": 2, "q_ja": "ジョーンズ さんがオフィスに行くと、窓が割れているのが----。", "a_ja": ["見つけること", "見つけるために（結果）", "見つけた", "見つける"]},
    "These shoes are (     ) than comfortable.": {"anum": 2, "q_ja": "この靴は快適というよりは----。", "a_ja": ["より可愛い", "可愛い", "より可愛い", "可愛い"]},
    "I stood (-----) for the train for more than one hour this evening.": {"anum": 0, "q_ja": "今晩、私は1時間以上電車を待って立っていた。", "answer": "waiting"},
    "She enjoys (     ) to pop music.": {"anum": 2, "q_ja": "彼女はポップミュージックを----のを楽しんでい る。", "a_ja": ["聴くこと", "聴くこと", "聴く", "聴いた"]},
    "It is very difficult (     ) the rule.": {"anum": 3, "q_ja": "----のは非常に難しい。", "a_ja": ["私が従う", "私が従った", "私が従うこと", "私が従うこと"]},
    "I (-----) Bill (-----) (-----) me with my English homework.": {"anum": 0, "q_ja": "私はビルに英語の宿題を手伝ってもらった。", "answer": "got to help"},
    "It is rare to see a (     ) in the river.": {"anum": 4, "q_ja": "川で----のを見るのは珍しい。", "a_ja": ["泳ぐ熊", "泳いだ熊", "熊が泳いだ", "熊が泳いでいる"]},
    "Aki hasn't decided (     ) to go for her summer vacation.": {"anum": 1, "q_ja": "アキは夏休みに----へ行くかまだ決めていない。", "a_ja": ["どこ", "いつ", "何", "どのように"]},
    "My sister's hobby is (-----) (-----) photos.": {"anum": 0, "q_ja": "私の姉の趣味は写真を撮ることだ。", "answer": "taking pictures"},
    "I remember Mike (     ) lots of mistakes in his childhood.": {"anum": 1, "q_ja": "私はマイクが子供の頃にたくさんの間違いをしたのを覚えている。", "a_ja": ["したこと", "する", "する", "すること"]},
    "What (     ) in that country?": {"anum": 1, "q_ja": "その国では----か？", "a_ja": ["話されている言語は何か", "話している言語は何か", "話している言語は何か", "言語は話されている"]},
    "I (-----) Mary (-----) the street.": {"anum": 0, "q_ja": "私はメアリーが通りを渡るのを見た。", "answer": "saw cross"},
    "She didn't know (-----) (-----) (-----) on the bus.": {"anum": 0, "q_ja": "彼女はバスでどこに座ればいいかわからなかった。", "answer": "where to sit"},
    "(     ) from what he says, the situation is bad.": {"anum": 4, "q_ja": "彼の言うことから----、状況は悪い。", "a_ja": ["判断する", "判断される", "判断", "判断すると"]},
    "(     ) from a distance, David looks like his father.": {"anum": 3, "q_ja": "遠くから----、デビッ ドは父親に似ている。", "a_ja": ["見ること", "見ること", "見られると", "見た"]},
    "He stopped (answer) the phone and talked for a while on the phone.": {"anum": 0, "q_ja": "彼は電話に出るために立ち止まり、しばらく電話で話した。", "answer": "to answer"},
    "Last weekend Anne's parents let her (     ) to the concert.": {"anum": 3, "q_ja": "先週末、アンの両親は彼女がコンサートに----のを許した。", "a_ja": ["行った", "行くこと", "行く", "行くこと"]},
    "I felt my (     ) by someone.": {"anum": 3, "q_ja": "私は誰かに----のを感じた。", "a_ja": ["つかんでいる肩", "肩がつかんでいる", "肩をつかまれる", "つかまれた肩"]},
    "My parents were delighted (-----) (-----) about my excellent grades.": {"anum": 0, "q_ja": "両親は私の素晴らしい成績を聞いて喜んだ。", "answer": "to hear"},
    "I'm so happy that I (-----) like (-----).": {"anum": 0, "q_ja": "私は泣きたいくらい嬉しい。", "answer": "feel crying"},
    "The (-----) (-----) on the bench was separated from his mother.": {"anum": 0, "q_ja": "ベンチで泣いている少年は母親とはぐれてしまった。", "answer": "boy crying"},
    "My grandfather often said that (     ) is more precious than peace.": {"anum": 4, "q_ja": "祖父はよ く、平和ほど貴重なものは----と言っていた。", "a_ja": ["何か", "何か", "全て", "何もない"]},
    "Time is more precious than (     ).": {"anum": 3, "q_ja": "時間は----貴重だ。", "a_ja": ["全て", "何もない", "他の何か", "全てのもの"]},
    "We all should try (     ) late for our important business meeting.": {"anum": 1, "q_ja": "私たちは皆、重要なビジネス会議に----努めるべきだ。", "a_ja": ["遅れないように", "遅れない", "遅れない", "遅れない"]},
    "Mike refused (stay) at the hotel in the mountains.": {"anum": 0, "q_ja": "マイクは山にあるそのホテルに泊まるのを拒否した。", "answer": "to stay"},
    "She is (     ) a scholar as a journalist.": {"anum": 2, "q_ja": "彼女は学者----ジャーナリス トだ。", "a_ja": ["全く～ない", "～というよりはむしろ", "～と同じくらい", "～に劣らず"]},
    "She asked me (-----) (-----) (-----) the medicine.": {"anum": 0, "q_ja": "彼女は私にその薬をいつ飲むべきか尋ねた。", "answer": "when to take"},
    "He kept (-----) (-----) the radio for several hours last night.": {"anum": 0, "q_ja": "彼は昨夜数時間ラジオを聴き続けた。", "answer": "listening to"},
    "Try (-----) (-----) (-----) too much.": {"anum": 0, "q_ja": "あまり心配しないようにしなさい。", "answer": "not to worry"},
    "We are looking forward (     ) your family.": {"anum": 3, "q_ja": "私たちはあなたのご家族に----のを楽しみにしています。", "a_ja": ["会うこと", "会うこと", "会うことへ", "会う"]},
    "(-----) (-----) busy, she went shopping.": {"anum": 0, "q_ja": "忙しくなかったので、彼女は買い物に行った。", "answer": "Not being"},
    "I'm sorry for (-----) (-----) you.": {"anum": 0, "q_ja": "お待たせしてすみません。", "answer": "having kept"},
    "(     ) went on, the more tired the players became.": {"anum": 2, "q_ja": "----長引くほど、選手たちは疲れていった。", "a_ja": ["より長い試合", "試合が長引けば", "長い試合", "最も長い試合"]},
    "She heard her name (     ) from behind.": {"anum": 4, "q_ja": "彼女は後ろから自分の名前が----のを聞いた。", "a_ja": ["呼ぶ", "呼ぶこと", "呼んでいる", "呼ばれる"]},
    "The poor baby elephant was found (     ) from its mother in the eastern part of Sri Lanka.": {"anum": 4, "q_ja": "そのかわいそうな子象は、スリランカ東部で母親と----のが見つかった。", "a_ja": ["選んでいる", "選ばれた", "分けている", "はぐれた"]},
    "Bob carelessly left his umbrella on the train.\nIt was careless (-----) Bob (-----) (-----) his umbrella on the train.": {"anum": 0, "q_ja": "電車に傘を置き忘れるなんて、ボブは不注意だった。", "answer": "of to leave"},
    "I hurried (     ) not to miss the train.": {"anum": 4, "q_ja": "私は電車に----急いだ。 ", "a_ja": ["～のような", "～のような", "～のために", "～するように"]},
    "(-----) you ready (-----) start?": {"anum": 0, "q_ja": "始める準備はできていますか？", "answer": "Are to"},
    "Keiko is pleased (     ) her close friend.": {"anum": 4, "q_ja": "ケイコは親友に----喜んでいる。", "a_ja": ["会った", "会うために", "会う", "会って"]},
    "(-----) newspapers is sometimes (-----).": {"anum": 0, "q_ja": "新聞を読むことは時々退屈だ。", "answer": "Reading boring"},
    "I decided to give up the idea of (     ) a house for the time being.": {"anum": 1, "q_ja": "私は当分 の間、家を----考えをあきらめることにした。", "a_ja": ["買うこと", "買うこと", "買う", "買った"]},
    "I have (     ) many DVDs as Josh.": {"anum": 4, "q_ja": "私はジョシュの----のDVDを持っている。", "a_ja": ["2倍", "2倍", "2倍", "2倍"]},
    "(     ) with what he had written before, his new mystery novel was not very thrilling.": {"anum": 4, "q_ja": "以前書いたものと----、彼の新しい推理小説はあまりスリリングではなかった。", "a_ja": ["比べること", "比べる", "比べて", "比べると"]},
    "She could not make herself (     ) in English when she tried to show the stranger the way to the station.": {"anum": 4, "q_ja": "彼女が見知らぬ人に駅への道を教えようとしたとき、彼女の英語は----なかった。", "a_ja": ["理解している", "理解する", "理解されること", "理解される"]},
    "I decided (-----) (-----) (-----) the soccer team.": {"anum": 0, "q_ja": "私はサッカーチームに参加しないことに決めた。", "answer": "not to join"},
    "There (     ) no further problems to discuss, we called off the meeting.": {"anum": 3, "q_ja": "議論 すべき問題がこれ以上----、私たちは会議を中止した。", "a_ja": ["ある", "ある", "あって", "ある"]},
    "She promised (buy) me a present for my birthday.": {"anum": 0, "q_ja": "彼女は私の誕生日にプレゼントを買うと約束した。", "answer": "to buy"},
    "If you find that book (     ), I'll buy and read it, too.": {"anum": 1, "q_ja": "もしその本が----と思ったら、私も買って読みます。", "a_ja": ["面白い", "興味", "興味を持って", "興味を持たれる"]},
    "Michael got up early (     ) be in time for the first train.": {"anum": 1, "q_ja": "マイケルは始発電 車に----早起きした。", "a_ja": ["～するのに十分", "～する時間", "～しないように", "～するように"]},
    "My father (-----) me (-----) (-----) a scientist.": {"anum": 0, "q_ja": "父は私に科学者になってほしいと思っている。", "answer": "wants to be"},
    "Have you ever considered (     ) in physics at college?": {"anum": 3, "q_ja": "大学で物理学を----と考えたことはありますか？", "a_ja": ["専攻すること", "専攻することについて", "専攻すること", "専攻することの"]},
    "I hope (    ) in Canada next year.": {"anum": 4, "q_ja": "来年カナダで----と思っている。", "a_ja": ["勉強すること", "勉強することへ", "勉強する", "勉強すること"], "answer": "to study"},
    "My mother (     ) me wait outside the store.": {"anum": 4, "q_ja": "母は私を店の外で----。", "a_ja": ["させた", "言った", "期待した", "させた"]},
    "Remember (give) it back to me tomorrow.": {"anum": 0, "q_ja": "明日それを私に返すのを覚えておいてね。", "answer": "to give"},
}

process_file('glammer-2A.csv', data)
