from process_csv import process_file

data = {
    "She ----- a carpet across the room.": {"anum": 4, "q_ja": "彼女は部屋いっぱいにカーペットを----た。", "a_ja": ["理解した", "持ち上げた", "批判した", "広げた"]},
    "You will soon ----- French if you live in Paris.": {"anum": 2, "q_ja": "パリに住めばすぐにフランス語を----だろう。", "a_ja": ["修繕する", "習得する", "扱う", "数える"]},
    "Modern ----- is strongly influenced by science.": {"anum": 2, "q_ja": "現代----は科学の影響を強く受けている。", "a_ja": ["生き物", "文明", "熱", "力"]},
    "The ----- stadium was built in 2019.": {"anum": 1, "q_ja": "その----スタジアムは2019年に建設された。", "a_ja": ["巨大な", "乾燥した", "タフな", "うるさい"]},
    "Dirty plates were ----- high in the sink.": {"anum": 3, "q_ja": "汚れた皿が流し台に高く----。", "a_ja": ["拒否された", "避けられた", "積み上げられた", "罰せられた"]},
    "She ----- a piece of paper in half.": {"anum": 2, "q_ja": "彼女は紙を半分に----。", "a_ja": ["積み上げた", "折った", "広げた", "閉めた"]},
    "I don't like ----- music very much.": {"anum": 2, "q_ja": "私は----音楽はあまり好きではない。", "a_ja": ["巨大な", "うるさい", "図", "閉めた"]},
    "The food aid program is ----- help the poor people.": {"anum": 1, "q_ja": "食糧援助プログラムは貧しい人々を助ける----。", "a_ja": ["ことになっている", "かつて～だった", "すべきだ", "したほうがよい"]},
    "-----, or you'll miss the train.": {"anum": 3, "q_ja": "----、そうしないと電車に乗り遅れるよ。", "a_ja": ["気をつけて", "試着して", "急げ", "待って"]},
    "Ann is upstairs.  ----- Tom, I have no idea where he is.": {"anum": 2, "q_ja": "アンは2階にいる。トム----、彼がどこにいるのか全く分からない。", "a_ja": ["まず第一に", "～に関しては", "現在は", "その結果"]},
    "I have a picture of him in my mind - tall, blond and -----.": {"anum": 2, "q_ja": "私の心の中に彼のイメージがある。背が高く、金髪で、----。", "a_ja": ["役立つ", "ハンサムな", "適した", "快適な"]},
    "The monkey hung from a tree by its -----.": {"anum": 2, "q_ja": "その猿は----で木にぶら下がっていた。", "a_ja": ["毛皮", "尻尾", "脳", "昆虫"]},
    "The museum is ----- visiting.": {"anum": 4, "q_ja": "その博物館は訪れる----。", "a_ja": ["適した", "理想的な", "過去", "価値がある"]},
    "Anyone can ----- this video camera easily.": {"anum": 2, "q_ja": "誰でも簡単にこのビデオカメラを----できる。", "a_ja": ["組織する", "操作する", "反射する", "伸ばす"]},
    "The ----- of the doctor's bill is $100.": {"anum": 4, "q_ja": "医者の請求----は100ドルだ。", "a_ja": ["量", "不足", "広がり", "額"]},
    "Please ----- a little longer.  She is on another call now but will be with you soon.": {"anum": 4, "q_ja": "もう少し----ください。彼女は今別の電話に出ていますが、すぐに代わります。", "a_ja": ["記入して", "気をつけて", "試着して", "待って"]},
    "A ----- of snow blocked the door.": {"anum": 1, "q_ja": "雪の----がドアをふさいだ。", "a_ja": ["塊", "不足", "レベル", "正方形"]},
    "The weather is bad today, and ----- that outfit won't do.": {"anum": 1, "q_ja": "今日は天気が悪いし、----その服装ではだめだ。", "a_ja": ["まず第一に", "現在は", "少しずつ", "～に関しては"]},
    "We discussed ----- warming in class.": {"anum": 2, "q_ja": "私たちは授業で----温暖化について議論した。", "a_ja": ["一般的な", "地球", "定期的な", "正常な"]},
    "Canada and Italy ----- diplomatic relations in 1970.": {"anum": 4, "q_ja": "カナダとイタリアは1970年に外交関係を----。", "a_ja": ["じっと見た", "数えた", "修理した", "樹立した"]},
    "We walked ----- the bus stop.": {"anum": 3, "q_ja": "私たちはバス停を----歩いた。", "a_ja": ["年上の", "最新の", "通り過ぎて", "毛皮"]},
    "We are supplied with only a small ----- of food.": {"anum": 1, "q_ja": "私たちは少----の食料しか供給されていない。", "a_ja": ["量", "円", "合計", "枚"]},
    "\"This tea is -----.\"  \"Thank you.  We got it while we were in China.\"": {"anum": 4, "q_ja": "「このお茶は----ですね。」「ありがとう。中国にいた時に手に入れたんです。」", "a_ja": ["快適な", "ハンサムな", "礼儀正しい", "美味しい"]},
    "Drunk driving is against the -----.": {"anum": 3, "q_ja": "飲酒運転は----違反だ。", "a_ja": ["適切な", "敵", "法律", "文明"]},
    "They have a very high ----- of English conversation ability.": {"anum": 4, "q_ja": "彼らは英会話能力の非常に高い----を持っている。", "a_ja": ["列", "額", "塊", "レベル"]},
    "The army prevented the ----- from entering the city.": {"anum": 3, "q_ja": "軍隊は----が市内に入るのを防いだ。", "a_ja": ["文明", "国", "敵", "地域社会"]},
    "This bike ----- to me.": {"anum": 1, "q_ja": "この自転車は私----。", "a_ja": ["のものだ", "話す", "回る", "準備ができている"]},
    "There are airports in all the ----- cities.": {"anum": 3, "q_ja": "すべての----都市には空港がある。", "a_ja": ["広がり", "うるさい", "主要な", "塊"]},
    "Spain is one of the ----- in the EU.": {"anum": 2, "q_ja": "スペインはEU加盟----の一つだ。", "a_ja": ["政策", "国", "地域社会", "制度"]},
    "This is the most ----- chair I've ever sat on.": {"anum": 2, "q_ja": "これは私が今まで座った中で最も----椅子だ。", "a_ja": ["礼儀正しい", "快適な", "価値がある", "ハンサムな"]},
    "She ----- at the children to stop.": {"anum": 2, "q_ja": "彼女は子供たちにやめるように----。", "a_ja": ["伸ばした", "叫んだ", "加熱した", "習得した"]},
    "My old friend comes to see me -----.": {"anum": 1, "q_ja": "私の旧友は----私に会いに来る。", "a_ja": ["時々", "少しずつ", "次々と", "現在は"]},
    "Heat ----- water into steam.": {"anum": 3, "q_ja": "熱は水を蒸気に----。", "a_ja": ["立つ", "待つ", "変える", "急ぐ"]},
    "My colleagues left the company -----.": {"anum": 3, "q_ja": "同僚たちは----会社を辞めた。", "a_ja": ["現在は", "ますます", "次々と", "まず第一に"]},
    "Please ----- for my grandmother while I am away.": {"anum": 2, "q_ja": "私が留守の間、祖母を----ください。", "a_ja": ["通り過ぎる", "気をつける（世話をする）", "捨てる", "立つ"]},
    "Overheating is not just a problem for the ----- people.": {"anum": 4, "q_ja": "熱中症は----人々だけの問題ではない。", "a_ja": ["適切な", "賢い", "脳", "高齢の"]},
    "A large engine usually has more ----- than a small one.": {"anum": 4, "q_ja": "大きなエンジンは通常、小さなエンジンよりも----がある。", "a_ja": ["システム", "役立つ", "太陽の", "パワー"]},
    "These plants grow well in a ----- climate.": {"anum": 3, "q_ja": "これらの植物は----気候でよく育つ。", "a_ja": ["怠惰な", "醜い", "乾燥した", "うるさい"]},
    "My brother often talks to ----- when he's working at desk.": {"anum": 4, "q_ja": "兄は机で仕事をしている時、よく----。", "a_ja": ["彼", "自分自身", "彼の", "独り言を言う"]},
    "Some parts of the city are rather -----.": {"anum": 1, "q_ja": "その都市の一部はかなり----。", "a_ja": ["醜い", "怠惰な", "青白い", "定期的な"]},
    "The lawyer gave me some ----- advice.": {"anum": 1, "q_ja": "弁護士は私にいくつかの----助言をくれた。", "a_ja": ["役立つ", "年上の", "力", "価値がある"]},
    "You look -----.  You should lie down and rest.": {"anum": 2, "q_ja": "----よ。横になって休んだ方がいい。", "a_ja": ["特定の", "顔色が悪い", "罰する", "積み上げる"]},
    "The ----- feeling among her friends is that she is a kind person.": {"anum": 1, "q_ja": "彼女の友人たちの間の----認識は、彼女が親切な人だということだ。", "a_ja": ["一般的な", "鈍い", "汚い", "醜い"]},
    "We would like to contribute to the ----- through volunteer activities.": {"anum": 1, "q_ja": "私たちはボランティア活動を通じて----に貢献したい。", "a_ja": ["地域社会", "優秀な", "敵", "力"]},
    "She could not ----- her own opinion.": {"anum": 3, "q_ja": "彼女は自分の意見を----ことができなかった。", "a_ja": ["楽しい", "政策", "述べる", "価値がある"]},
    "Mobile phones play an important role in the ----- life.": {"anum": 1, "q_ja": "携帯電話は----生活において重要な役割を果たしている。", "a_ja": ["現代の", "昆虫", "最新の", "太陽の"]},
    "He is an ----- teacher.": {"anum": 4, "q_ja": "彼は----教師だ。", "a_ja": ["楽しい", "賢い", "ハンサムな", "優秀な"]},
    "The letters \"U.N.\" ----- \"United Nations.\"": {"anum": 4, "q_ja": "「U.N.」という文字は「国際連合」を----。", "a_ja": ["記入する", "待つ", "試着する", "表す"]},
    "Failure changed his -----.": {"anum": 1, "q_ja": "失敗が彼の----を変えた。", "a_ja": ["考え", "修繕する", "脳", "尻尾"]},
    "We ----- each other when the game was over.": {"anum": 2, "q_ja": "試合が終わった時、私たちはお互いに----。", "a_ja": ["試着した", "握手した", "急いだ", "記入した"]},
    "The teacher ----- each word slowly.": {"anum": 2, "q_ja": "先生は各単語をゆっくりと----。", "a_ja": ["叫んだ", "発音した", "扱った", "組織した"]},
    "I ----- to the police about the noise.": {"anum": 3, "q_ja": "私は騒音について警察に----。", "a_ja": ["拒否した", "叱った", "苦情を言った", "罰した"]},
    "The father ----- his son for getting poor marks in the exam.": {"anum": 3, "q_ja": "父親は試験の点数が悪かったことで息子を----。", "a_ja": ["避けた", "折った", "叱った", "苦情を言った"]},
    "We can divide the ----- cost among us and pay separately.": {"anum": 3, "q_ja": "私たちは----費用を私たちで分けて別々に支払うことができる。", "a_ja": ["額", "塊", "合計の", "不足"]},
    "I almost couldn't ----- my suitcase.": {"anum": 1, "q_ja": "私はスーツケースをもう少しで----ことができなかった。", "a_ja": ["閉める", "叱る", "苦情を言う", "伸ばす"]},
    "You ----- make more time for yourself to relax.": {"anum": 2, "q_ja": "あなたはリラックスするために自分の時間をもっと作る----。", "a_ja": ["するつもりだ", "すべきだ", "慣れている", "ことになっている"]},
    "----- holes and tears in clothes before you wash them.": {"anum": 3, "q_ja": "洗濯する前に服の穴やほころびを----なさい。", "a_ja": ["習得しろ", "数えろ", "修繕しろ", "組織しろ"]},
    "\"Are you ----- order?\"  \"Yes, I'd like a steak meal.\"": {"anum": 1, "q_ja": "「注文の----はできましたか？」「はい、ステーキ定食をお願いします。」", "a_ja": ["準備", "喜んで～する", "可能性が高い", "ことになっている"]},
    "A lot of ----- animals live on this island.": {"anum": 1, "q_ja": "この島には多くの----動物が住んでいる。", "a_ja": ["珍しい", "失礼な", "定期的な", "合計の"]},
    "The ----- residents are excited at the news.": {"anum": 3, "q_ja": "----住民はそのニュースに興奮している。", "a_ja": ["珍しい", "四角い", "地元の", "円"]},
    "I was ----- enough to quit the band.": {"anum": 2, "q_ja": "バンドを辞めるなんて私は----だった。", "a_ja": ["苦情を言う", "愚かな", "顔色が悪い", "地元の"]},
    "The factory uses the very ----- technology.": {"anum": 3, "q_ja": "その工場はまさに----技術を使用している。", "a_ja": ["叫び", "尻尾", "最新の", "じっと見る"]},
    "He was ----- for drunk driving.": {"anum": 3, "q_ja": "彼は飲酒運転で----。", "a_ja": ["修繕された", "閉められた", "罰せられた", "扱われた"]},
    "-----, they stopped talking and looked at me.": {"anum": 2, "q_ja": "----、彼らは話すのをやめて私を見た。", "a_ja": ["～に関しては", "突然", "現在は", "ますます"]},
    "There is a ----- of beautiful houses along the street.": {"anum": 3, "q_ja": "通り沿いに美しい家々の----がある。", "a_ja": ["積み重ね", "合計", "並び", "量"]},
    "I have no ----- reason to refuse his invitation.": {"anum": 1, "q_ja": "彼の招待を断る----理由は私にはない。", "a_ja": ["特定の", "珍しい", "地元の", "地球の"]},
    "My friend brought home a TV set that had been -----.": {"anum": 4, "q_ja": "私の友人は----テレビセットを家に持ち帰った。", "a_ja": ["通り過ぎた", "記入した", "待った", "捨てられた"]},
    "Please show me the ----- way to make coffee.": {"anum": 1, "q_ja": "コーヒーの----淹れ方を教えてください。", "a_ja": ["適切な", "高齢の", "年下の", "ハンサムな"]},
    "Women ----- live longer than men.": {"anum": 3, "q_ja": "女性は男性よりも長生きする----。", "a_ja": ["表す", "変わる", "傾向がある", "準備ができている"]},
    "If you ----- keep your promises, those around you will take your words less seriously.": {"anum": 2, "q_ja": "もし約束を守るのを----と、周りの人はあなたの言葉をあまり真剣に受け取らなくなるだろう。", "a_ja": ["表す", "怠る", "記入する", "傾向がある"]},
    "The teacher drew a ----- on the blackboard.": {"anum": 1, "q_ja": "先生は黒板に----を描いた。", "a_ja": ["円", "量", "枚", "額"]},
    "You should exercise on a ----- basis.": {"anum": 1, "q_ja": "あなたは----に運動すべきだ。", "a_ja": ["定期的な", "恐ろしい", "珍しい", "失礼な"]},
    "White walls ----- more light than dark walls.": {"anum": 3, "q_ja": "白い壁は暗い壁よりも多くの光を----。", "a_ja": ["伸ばす", "操作する", "反射する", "修繕する"]},
    "They were involved in an ----- accident and are still suffering from the damage.": {"anum": 3, "q_ja": "彼らは----事故に巻き込まれ、今でもその被害に苦しんでいる。", "a_ja": ["恐ろしい", "鈍い", "ひどい", "愚かな"]},
    "We ----- a concert for our school festival.": {"anum": 4, "q_ja": "私たちは学園祭のためにコンサートを----。", "a_ja": ["操作した", "習得した", "樹立した", "企画した"]},
    "Water turns into steam when it is -----.": {"anum": 2, "q_ja": "水は----と蒸気になる。", "a_ja": ["発砲された", "加熱された", "太陽の", "操作された"]},
    "I ----- getting on a train during rush hour.": {"anum": 2, "q_ja": "私はラッシュアワーに電車に乗るのを----。", "a_ja": ["鈍い", "拒否する", "恐ろしい", "避ける"]},
    "How much will it cost to ----- the car?": {"anum": 4, "q_ja": "その車を----のにいくらかかりますか？", "a_ja": ["組織する", "じっと見る", "操作する", "修理する"]},
    "He ----- at me in surprise.": {"anum": 2, "q_ja": "彼は驚いて私を----。", "a_ja": ["発音した", "じっと見た", "伸ばした", "反射した"]},
    "I don't have time to talk about this now.  Go away and ----- me alone.": {"anum": 1, "q_ja": "今はこれについて話す時間がない。あっちへ行って私を----くれ。", "a_ja": ["放っておいて", "閉めて", "押して", "折って"]},
    "She turned ----- an offer to be introduced to a rich man.": {"anum": 3, "q_ja": "彼女は金持ちの男性を紹介するという申し出を----。", "a_ja": ["～へ", "～の上", "断った", "判明した"]},
    "A lot of taxis ----- while I was waiting for a bus.": {"anum": 2, "q_ja": "バスを待っている間に多くのタクシーが----。", "a_ja": ["気をつけた", "失敗した", "待った", "通り過ぎた"]},
    "The story got ----- exciting.": {"anum": 1, "q_ja": "その物語は----面白くなった。", "a_ja": ["ますます", "次々と", "～に関しては", "現在は"]},
    "The government ----- to give in to the demands of the terrorists.": {"anum": 3, "q_ja": "政府はテロリストの要求に屈することを----。", "a_ja": ["達した", "避けた", "拒否した", "苦情を言った"]},
    "I ----- the antenna on my radio to its full length.": {"anum": 4, "q_ja": "私はラジオのアンテナをいっぱいに----。", "a_ja": ["発砲した", "反射した", "数えた", "伸ばした"]},
    "It was dark, so I turned ----- the light.": {"anum": 1, "q_ja": "暗かったので、私は明かりを----。", "a_ja": ["つけた", "消した", "回した", "～へ"]},
    "My ----- brother looks nothing like me.": {"anum": 3, "q_ja": "私の----は私と全く似ていない。", "a_ja": ["過去", "最新の", "兄", "現代の"]},
    "I've never ----- of such a thing.  Is that true?": {"anum": 4, "q_ja": "そんなことは----ことがない。本当ですか？", "a_ja": ["作った", "所属した", "話した", "聞いた"]},
    "I can't write with this ----- pencil.": {"anum": 2, "q_ja": "この----鉛筆では書けない。", "a_ja": ["失礼な", "丸くなった", "円", "青白い"]},
    "The recipe recommends that you use a ----- cake tin.": {"anum": 3, "q_ja": "そのレシピは----ケーキ型を使うことを勧めている。", "a_ja": ["不足", "塊", "四角い", "列"]},
    "I've had no ----- to read recently.": {"anum": 3, "q_ja": "最近は読書をする----がない。", "a_ja": ["図", "価値", "暇", "脳"]},
    "People who experience high stress are ----- get sick.": {"anum": 4, "q_ja": "高いストレスを感じている人は病気になる----。", "a_ja": ["喜んで～する", "かつて～だった", "ことになっている", "可能性が高い"]},
    "I picked up a ----- leaf from the ground.": {"anum": 2, "q_ja": "私は地面から----葉を拾った。", "a_ja": ["タフな", "ちっぽけな", "列", "うるさい"]},
    "The girl came home from the playground wearing a ----- shirt.": {"anum": 1, "q_ja": "少女は----シャツを着て遊び場から帰ってきた。", "a_ja": ["汚れた", "愚かな", "愚かな", "失礼な"]},
    "The government is planning to change the education -----.": {"anum": 1, "q_ja": "政府は教育----を変えることを計画している。", "a_ja": ["制度", "警察", "適切な", "昆虫"]},
    "The plants died for ----- of water.": {"anum": 4, "q_ja": "植物は水----のために枯れた。", "a_ja": ["積み重ね", "鈍い", "恐ろしい", "不足"]},
    "He ----- the brake pedal.": {"anum": 3, "q_ja": "彼はブレーキペダルを----。", "a_ja": ["ノックした", "折った", "踏んだ", "伸ばした"]},
    "You ----- call him and apologize before it is too late.": {"anum": 1, "q_ja": "手遅れになる前に彼に電話して謝った----。", "a_ja": ["方がよい", "準備ができている", "慣れている", "かつて～だった"]},
    "I need three ----- of paper.": {"anum": 4, "q_ja": "紙が3----必要だ。", "a_ja": ["列", "額", "図", "枚"]},
    "I ----- be afraid of dogs, but now I like them.": {"anum": 1, "q_ja": "「私は----犬が怖かったが、今は好きだ。」", "a_ja": ["かつて", "可能性が高い", "慣れている", "しなければならない"]},
    "Remember to turn ----- the air conditioner when you leave home.": {"anum": 4, "q_ja": "家を出る時はエアコンを----のを忘れないで。", "a_ja": ["回す", "～へ", "消す", "消す"]},
    "Did you report the robbery to the -----?": {"anum": 2, "q_ja": "強盗を----に通報しましたか？", "a_ja": ["法律", "警察", "州", "政策"]},
    "I spent a ----- weekend with a friend of mine.": {"anum": 3, "q_ja": "私は友人と----週末を過ごした。", "a_ja": ["過去", "役立つ", "楽しい", "賢い"]},
    "Vitamin D helps to maintain ----- heartbeat.": {"anum": 2, "q_ja": "ビタミンDは----心拍を維持するのに役立つ。", "a_ja": ["珍しい", "正常な", "地元の", "特定の"]},
    "It is ----- of you to ignore the guests.": {"anum": 3, "q_ja": "客を無視するなんてあなたは----だ。", "a_ja": ["一般的な", "拒否された", "失礼な", "避けられた"]},
    "It is not ----- of you to make noise at the table.": {"anum": 4, "q_ja": "食事中に音を立てるのは----ことではない。", "a_ja": ["楽しい", "役立つ", "適切な", "礼儀正しい"]},
    "He was ----- help me with the preparations.": {"anum": 1, "q_ja": "彼は----準備を手伝ってくれた。", "a_ja": ["喜んで", "したほうがよい", "かつて", "すべきだ"]},
    "I'm looking forward to hearing ----- you soon.": {"anum": 2, "q_ja": "すぐにあなた----連絡が来るのを楽しみにしています。", "a_ja": ["～へ", "～から", "～の", "～について"]},
    "Contrary to popular belief, gorillas are basically shy, gentle -----.": {"anum": 3, "q_ja": "一般に信じられていることとは反対に、ゴリラは基本的には内気で優しい----だ。", "a_ja": ["尻尾", "昆虫", "生き物", "主人"]},
    "Everything is going well -----.": {"anum": 4, "q_ja": "----すべて順調にいっている。", "a_ja": ["まず第一に", "突然", "ますます", "現在は"]},
    "Do you agree with the government ----- on education?": {"anum": 3, "q_ja": "あなたは政府の教育----に賛成ですか？", "a_ja": ["国", "優秀な", "政策", "賢い"]},
    "Hurry up!  The boss will be here in ----- an hour.": {"anum": 4, "q_ja": "急げ！上司は1時間----でここに来るぞ。", "a_ja": ["以上", "～もの", "～もの", "未満"]},
    "I ----- work part-time on Sunday afternoon.": {"anum": 1, "q_ja": "私は日曜日の午後にアルバイトを----。", "a_ja": ["しなければならない", "ことになっている", "喜んで～する", "可能性が高い"]},
    "----- he became accepted by the family.": {"anum": 3, "q_ja": "----彼は家族に受け入れられるようになった。", "a_ja": ["～に関しては", "次々と", "少しずつ", "現在は"]},
    "We made ----- changes to the schedule.": {"anum": 3, "q_ja": "私たちはスケジュールに----変更を加えた。", "a_ja": ["青白い", "鈍い", "些細な", "汚れた"]},
    "The amusement park is an ----- spot for dating.": {"anum": 2, "q_ja": "その遊園地はデートに----場所だ。", "a_ja": ["価値がある", "理想的な", "快適な", "適した"]},
    "I've finally gotten ----- riding in overcrowded trains.": {"anum": 3, "q_ja": "私はついに満員電車に乗ることに----。", "a_ja": ["準備ができている", "喜んで～する", "慣れた", "可能性が高い"]},
    "We didn't even have the ----- to stand up.": {"anum": 2, "q_ja": "私たちには立ち上がる----さえなかった。", "a_ja": ["適した", "体力", "法律", "楽しい"]},
    "The teacher ----- the children as they got on the bus.": {"anum": 4, "q_ja": "先生はバスに乗る子供たちを----。", "a_ja": ["習得した", "樹立した", "修理した", "数えた"]},
    "----- this hat and see if it fits you.": {"anum": 1, "q_ja": "この帽子を----、合うかどうか見てみなさい。", "a_ja": ["試着して", "捨てて", "傾向があって", "記入して"]},
    "John is ----- to me by two years.": {"anum": 4, "q_ja": "ジョンは私より2歳----だ。", "a_ja": ["最新の", "現代の", "過去", "年上"]},
    "Birds and ----- lay eggs.": {"anum": 4, "q_ja": "鳥や----は卵を産む。", "a_ja": ["生き物", "尻尾", "脳", "昆虫"]},
    "That movie is a smash hit all over the world, and has been screened in ----- 100 countries.": {"anum": 3, "q_ja": "「あの映画は世界中で大ヒットし、100カ国----で上映されている。」", "a_ja": ["未満", "ますます", "以上", "～もの"]},
    "His son is a very ----- boy.  He has the best grades in his class.": {"anum": 3, "q_ja": "彼の息子はとても----少年だ。彼はクラスで一番の成績をとっている。", "a_ja": ["礼儀正しい", "価値がある", "賢い", "ハンサムな"]},
    "He wrote ----- ten books.": {"anum": 2, "q_ja": "彼は10冊----本を書いた。", "a_ja": ["突然", "～もの", "～もの", "ますます"]},
    "I can't ----- out how to get there.": {"anum": 4, "q_ja": "そこへの行き方が----ない。", "a_ja": ["レベル", "円", "正方形", "わから"]},
    "Please ----- hello to your mother for me.": {"anum": 3, "q_ja": "お母さんに私からよろしくと----おいてください。", "a_ja": ["伝えて", "話して", "言って", "話して"]},
    "She turned ----- and walked away without a word.": {"anum": 1, "q_ja": "彼女は----、一言も言わずに立ち去った。", "a_ja": ["振り向いて", "消えて", "断って", "～の上"]},
    "I can't ----- this box.  It's too heavy.": {"anum": 2, "q_ja": "この箱を----ことができない。重すぎる。", "a_ja": ["閉める", "持ち上げる", "押す", "折る"]},
    "What are you ----- to do this weekend?": {"anum": 1, "q_ja": "今週末は何を----ですか？", "a_ja": ["するつもり", "かつて～だった", "持っている", "すべき"]},
    "The journalist ----- the government policy severely.": {"anum": 2, "q_ja": "そのジャーナリストは政府の方針を厳しく----。", "a_ja": ["苦情を言った", "批判した", "罰した", "積み上げた"]},
    "The man turned ----- to be our new coach.": {"anum": 2, "q_ja": "その男は私たちの新しいコーチだと----。", "a_ja": ["～の上", "判明した", "振り向いた", "消した"]},
    "This house is made ----- wood.": {"anum": 2, "q_ja": "この家は木----作られている。", "a_ja": ["～の中へ", "～で（材料）", "～によって", "～から（原料）"]},
    "She is two years ----- to me at the office.": {"anum": 2, "q_ja": "彼女は会社で私の2年----だ。", "a_ja": ["過去", "後輩", "尻尾", "毛皮"]},
    "A ----- broke out in the boiler room yesterday.": {"anum": 1, "q_ja": "昨日ボイラー室で----が発生した。", "a_ja": ["火事", "取っ手", "熱", "力"]},
    "Please ----- the application form.": {"anum": 1, "q_ja": "申込用紙に----ください。", "a_ja": ["記入して", "握手して", "通り過ぎて", "傾向があって"]},
    "My ----- brother never cleans his room.": {"anum": 2, "q_ja": "私の----弟は決して部屋を掃除しない。", "a_ja": ["一般的な", "怠惰な", "珍しい", "地球の"]},
    "This sweater ----- me perfectly.": {"anum": 4, "q_ja": "このセーターは私に完璧に----。", "a_ja": ["快適な", "価値がある", "適切な", "合う"]},
    "The movie has a lot of ----- scenes.  It is not good for small children.": {"anum": 1, "q_ja": "その映画には----シーンがたくさんある。小さな子供には良くない。", "a_ja": ["恐ろしい", "地球の", "正常な", "怠惰な"]},
    "You have to be ----- to survive in life.": {"anum": 1, "q_ja": "人生を生き抜くには----なければならない。", "a_ja": ["たくましく", "恐ろしく", "ひどく", "失礼で"]},
    "Before you go in, ----- on the door.": {"anum": 2, "q_ja": "「入る前にドアを----なさい。」", "a_ja": ["持ち上げ", "ノックし", "閉め", "折り"]},
    "The situation is too complex for me to -----.": {"anum": 1, "q_ja": "状況は複雑すぎて私には----できない。", "a_ja": ["対処", "太陽", "脳", "力"]},
    "Messages from the ----- are carried by the central nervous system.": {"anum": 1, "q_ja": "----からのメッセージは中枢神経系によって運ばれる。", "a_ja": ["脳", "尻尾", "毛皮", "高齢者"]},
    "We can make wine ----- grapes.": {"anum": 2, "q_ja": "私たちはブドウ----ワインを作ることができる。", "a_ja": ["～の", "～から（原料）", "～によって", "～の中へ"]},
    "These caterpillars will turn ----- butterflies.": {"anum": 2, "q_ja": "これらの毛虫は蝶----。", "a_ja": ["判明する", "になる", "振り向く", "～の上"]},
    "There was a big earthquake, and ----- many people lost their houses.": {"anum": 4, "q_ja": "「大地震があり、----多くの人々が家を失った。」", "a_ja": ["少しずつ", "～に関しては", "時々", "その結果"]},
    "That machine produces no carbon emissions, thanks to ----- heating and clever design.": {"anum": 4, "q_ja": "「その機械は、----熱と巧みな設計のおかげで、炭素排出を生まない。」", "a_ja": ["力", "操作", "拡張", "太陽"]},
    "The ----- was soft to the touch.": {"anum": 4, "q_ja": "その----は手触りが柔らかかった。", "a_ja": ["じっと見る", "脳", "火", "毛皮"]},
    "She said to ----- that there was something wrong.": {"anum": 3, "q_ja": "彼女はどこかおかしいと----に言った（思った）。", "a_ja": ["自分自身", "彼女", "自分自身", "彼女のもの"]},
    "It was ----- of me to forget my passport.": {"anum": 1, "q_ja": "パスポートを忘れるなんて私は----だった。", "a_ja": ["愚か", "拒否された", "叱られた", "醜い"]},
}

process_file('1051~1200.csv', data)
