from process_csv import process_file

data = {
    "I think he is a very intelligent person, ----- many people don’t agree with me.": {"anum": 1, "q_ja": "彼はとても知的な人だと思う----、多くの人は私に同意しない。", "a_ja": ["が", "誰", "～のために", "どちら"]},
    "Because he ----- to deliver the package on time, there was nothing to give the boss for her birthday.": {"anum": 3, "q_ja": "彼が時間通りに荷物を届けるのを----ので、上司の誕生日にあげるものが何もなかった。", "a_ja": ["失った", "逃した", "怠った", "辞めた"]},
    "There are special seats at the stadium, ----- people can watch games with food and drinks.": {"anum": 2, "q_ja": "スタジアムには特別な席があり、----人々は飲食しながら試合観戦ができる。", "a_ja": ["どちら", "そこで", "その～", "あれ"]},
    "Jane has a dog ----- has long ears.": {"anum": 2, "q_ja": "ジェーンは耳の長い犬を飼っている。", "a_ja": ["何", "（関係代名詞）", "誰", "その～"]},
    "The chair ----- a cat is sleeping was made in Italy.": {"anum": 1, "q_ja": "猫が眠っている椅子はイタリア製だ。", "a_ja": ["その上で", "（関係代名詞）", "その～", "あれ"]},
    "Mr. Brett missed the train ----- he was working late.": {"anum": 4, "q_ja": "ブレット氏は遅くまで働いていた----電車に乗り遅れた。", "a_ja": ["後", "あれ", "まで", "ので"]},
    "If you ----- me for help, I would have helped you.": {"anum": 2, "q_ja": "もしあなたが私に助けを----なら、私はあなたを助けただろうに。", "a_ja": ["頼む", "頼んでいた", "頼んだ", "頼むだろう"]},
    "Our city is now very different from ----- it was twenty years ago.": {"anum": 4, "q_ja": "私たちの市は20年前の姿とは大きく異なっている。", "a_ja": ["どちら", "あれ", "なぜ", "もの"]},
    "He worked hard ----- he could pass the examination.": {"anum": 3, "q_ja": "彼は試験に合格----一生懸命勉強した。", "a_ja": ["～のために", "代わりに", "するように", "さもなければ"]},
    "I wish I ----- so much last night. Now I feel terrible.": {"anum": 1, "q_ja": "昨夜あんなに----よかったのに。今、気分がひどく悪い。", "a_ja": ["飲まなければ", "飲んでいない", "飲まない", "飲まないだろう"]},
    "----- the personal computer, it would be more difficult for us to contact people living in different time zones.": {"anum": 4, "q_ja": "パソコンが----、異なる時間帯に住む人々と連絡を取るのはもっと難しくなるだろう。", "a_ja": ["～があれば", "あれば", "もし～がなかったら", "なければ"]},
    "John ----- mistakes on his exam.": {"anum": 4, "q_ja": "ジョンは試験で----間違いをしなかった。", "a_ja": ["間違いをしない", "いくつか間違いをした", "ほとんど間違いをしなかった", "全く"]},
    "Although we met today for the first time, I feel as if you ----- my old friend.": {"anum": 2, "q_ja": "今日初めて会ったのに、まるであなたが私の旧友----ように感じる。", "a_ja": ["である", "である", "ようだ", "だろう"]},
    "----- on time, she would have had dinner with us.": {"anum": 4, "q_ja": "もし彼女が定時に退社----、私たちと一緒に夕食をとっていただろう。", "a_ja": ["退社できれば", "退社できるなら", "退社するなら", "できていれば"]},
    "As ----- as you come back home by ten, you may go out.": {"anum": 3, "q_ja": "10時までに帰ってくる----、外出してもよい。", "a_ja": ["遅く", "速く", "限り", "早く"]},
    "----- he listened to his mother, he might not have made such a mistake.": {"anum": 3, "q_ja": "もし彼が母親の言うことを----、そんな間違いはしなかったかもしれない。", "a_ja": ["すべき", "～でない限り", "聞いていれば", "想定された"]},
    "If it ----- for your help, I wouldn't have won the competition.": {"anum": 2, "q_ja": "もしあなたの助けが----、私はコンテストで優勝できなかっただろう。", "a_ja": ["なかったら", "なかったら", "ないなら", "ないなら"]},
    "I have an uncle ----- lives in Australia.": {"anum": 2, "q_ja": "私にはオーストラリアに住んでいる叔父がいる。", "a_ja": ["どこ", "（関係代名詞）", "どちら", "誰"]},
    "She comes from a country ----- political situation is unstable.": {"anum": 3, "q_ja": "彼女は政治情勢が不安定な国の出身だ。", "a_ja": ["あれ", "その", "その～", "どちら"]},
    "He said that he saw me there, ----- was a lie.": {"anum": 1, "q_ja": "彼はそこで私に会ったと言ったが、それは嘘だった。", "a_ja": ["それは", "その～", "あれ", "何"]},
    "John is 10cm shorter than Bill, ----- 10cm shorter than Tom; therefore John is 20cm shorter than Tom.": {"anum": 2, "q_ja": "ジョンはビルより10cm背が低く、ビルはトムより10cm背が低い。したがってジョンはトムより20cm背が低い。", "a_ja": ["その身長は", "そしてビルは", "その身長は", "ありえない"]},
    "It will be a long time ----- she can write as efficiently as her classmates. She has got a lot of catching up to do.": {"anum": 3, "q_ja": "彼女がクラスメートと同じくらい効率的に書けるようになる----長い時間がかかるだろう。彼女には取り戻すべきことがたくさんある。", "a_ja": ["かどうか", "までに", "前に", "前に"]},
    "Do you remember the girl ----- I introduced to you at the party?": {"anum": 3, "q_ja": "パーティーであなたに紹介した女の子を覚えていますか？", "a_ja": ["いつ", "どちら", "（関係代名詞）", "その～"]},
    "If you ----- to travel across West Africa, you would encounter more than 700 distinct languages.": {"anum": 3, "q_ja": "もし西アフリカを旅行----、700以上の異なる言語に出会うだろう。", "a_ja": ["持っていた", "すべき", "するなら", "できる"]},
    "This is the only problem ----- I couldn’t answer.": {"anum": 3, "q_ja": "これが私が答えられなかった唯一の問題だ。", "a_ja": ["誰", "その～", "（関係代名詞）", "誰"]},
    "A: Why aren't you ready to go? B: I'm ready. A: How can that be? It's freezing outside, ----- you're wearing shorts and a T-shirt.": {"anum": 2, "q_ja": "A: なぜ出かける準備ができていないの？ B: 準備できてるよ。 A: どうして？ 外は凍えるほど寒いのに、----あなたは短パンとTシャツを着ている。", "a_ja": ["～として", "それなのに", "～のために", "だから"]},
    "He didn't forget ----- his father had told him, so he didn't get into trouble.": {"anum": 2, "q_ja": "彼は父親が言った----を忘れなかったので、トラブルに巻き込まれなかった。", "a_ja": ["こと", "こと", "どちら", "～として"]},
    "The pizza ----- Jim made wasn’t so good.": {"anum": 3, "q_ja": "ジムが作ったピザはあまり美味しくなかった。", "a_ja": ["その～", "誰", "（関係代名詞）", "何"]},
    "----- that the room is painted yellow, it looks lovely and bright.": {"anum": 1, "q_ja": "部屋が黄色く塗られた----、素敵で明るく見える。", "a_ja": ["今や", "～以来", "～でない限り", "～ない"]},
    "If you ----- this person, please call me.": {"anum": 3, "q_ja": "もしこの人を----、私に電話してください。", "a_ja": ["見たら", "見るなら", "見かけたら", "見た"]},
    "I don’t know the reason ----- he got angry.": {"anum": 2, "q_ja": "彼が怒った----を知らない。", "a_ja": ["何", "理由", "いつ", "どちら"]},
    "----- a little more effort, you would have succeeded.": {"anum": 3, "q_ja": "もう少し努力----、あなたは成功していただろう。", "a_ja": ["～のために", "～がなければ", "～があれば", "～のおかげで"]},
    "That is the bus ----- goes to Chinatown.": {"anum": 2, "q_ja": "あれはチャイナタウンに行くバスだ。", "a_ja": ["どこ", "（関係代名詞）", "その～", "いつ"]},
    "“He’s a good skier, isn’t he?\"  \"Yes, he really is.  I wish I ----- like him.”": {"anum": 4, "q_ja": "「彼はスキーが上手だね。」「うん、本当に。彼のように----いいのに。」", "a_ja": ["滑るだろう", "滑る", "滑れる", "滑れたら"]},
    "I don’t think she will visit me, but if she ----- while I’m out, tell her more details about our company.": {"anum": 4, "q_ja": "彼女が私を訪ねてくるとは思わないが、もし私が留守の間に彼女が----、会社の詳細を伝えてください。", "a_ja": ["来るだろう", "来ていた", "来た", "万一来たら"]},
    "If he had listened to her, he ----- such a mistake.": {"anum": 1, "q_ja": "もし彼が彼女の言うことを聞いていたら、そんな間違いは----。", "a_ja": ["しなかったかもしれない", "しないだろう", "するかもしれない", "しただろう"]},
    "If I were wealthy, I ----- a ship.": {"anum": 2, "q_ja": "もし私が裕福なら、船を----。", "a_ja": ["買うだろう", "買うのに", "買える", "買っただろう"]},
    "If I knew the answer, I ----- you.": {"anum": 2, "q_ja": "もし答えを知っていたら、あなたに----。", "a_ja": ["教えるだろう", "教えられるのに", "教えられたのに", "教えられる"]},
    "-----, you should always check your answers again.": {"anum": 3, "q_ja": "試験が----、常に答えを見直すべきだ。", "a_ja": ["どんなに簡単でも", "どんなに簡単でも", "どんなに簡単でも", "どんなに簡単でも"]},
    "What bothers me is not what you said ----- the way you said it.": {"anum": 3, "q_ja": "私が気になっているのは、あなたが言ったことではなく、その言い方----。", "a_ja": ["間", "なぜなら", "だ", "～でない限り"]},
    "It is a rare situation ----- all involved would be happy.": {"anum": 4, "q_ja": "関係者全員が幸せになる----稀な状況だ。", "a_ja": ["場所", "何", "どちら", "ような"]},
    "If another world war ----- occur, it might be the end of the world.": {"anum": 3, "q_ja": "もしまた世界大戦が----、世界の終わりになるかもしれない。", "a_ja": ["ありうる", "だろう", "万一起これば", "かもしれない"]},
    "----- his advice, we would never have finished the work on time.": {"anum": 4, "q_ja": "彼の助言----、私たちは決して仕事を時間通りに終えられなかっただろう。", "a_ja": ["受け入れた", "除いて", "なければ", "がなければ"]},
    "A: Do you have much snow in your country? B: No, we ----- have any snow, but windy weather is common.": {"anum": 1, "q_ja": "A: あなたの国では雪がたくさん降りますか？ B: いいえ、雪は----降りませんが、風の強い天気は一般的です。", "a_ja": ["ほとんど～ない", "ただ", "少し", "どちらも～ない"]},
    "Chieko at last found a place ----- she was content to call home.": {"anum": 2, "q_ja": "チエコはついに家と呼んで満足できる場所を見つけた。", "a_ja": ["誰", "（関係代名詞）", "いつ", "何"]},
    "It won’t be long ----- Uncle Walt returns home from his travels.": {"anum": 1, "q_ja": "ウォルト叔父さんが旅行から帰ってくるまで----だろう。", "a_ja": ["まもなく", "いつ", "後", "間"]},
    "Do you remember the castle ----- you went ten years ago?": {"anum": 4, "q_ja": "10年前にあなたが行った城を覚えていますか？", "a_ja": ["どちら", "いつ", "何", "どこ"]},
    "----- I know, we have only two books on the subject in our library.": {"anum": 4, "q_ja": "私の知る----、当館にはその主題に関する本は2冊しかない。", "a_ja": ["はるかに", "決して～ない", "これまでのところ", "限り"]},
    "Make sure you do the homework, ----- you will be in trouble again.": {"anum": 1, "q_ja": "必ず宿題をやりなさい、----また困ったことになるよ。", "a_ja": ["さもなければ", "それから", "～のために", "そして"]},
    "The time may come soon ----- we will enjoy space travel.": {"anum": 1, "q_ja": "私たちが宇宙旅行を楽しめる時がすぐに来るかもしれない。", "a_ja": ["いつ", "どこ", "どちら", "～として"]},
    "If he ----- at the party, it would have been much more enjoyable.": {"anum": 4, "q_ja": "もし彼がパーティーに----、もっと楽しかっただろう。", "a_ja": ["いたら", "いた", "いる", "いたら"]},
    "Yokohama is the city ----- I was born.": {"anum": 4, "q_ja": "横浜は私が生まれた街だ。", "a_ja": ["あれ", "いつ", "どちら", "どこ"]},
    "From 2006 onwards he worked at the downtown library, ----- he became the director in 2014.": {"anum": 2, "q_ja": "2006年以降、彼はダウンタウンの図書館で働き、----2014年に館長になった。", "a_ja": ["間", "そこで", "どちら", "いつ"]},
    "I can’t forget the day ----- I first met you.": {"anum": 4, "q_ja": "私はあなたに初めて会った日を忘れることができない。", "a_ja": ["どう", "どこ", "何", "いつ"]},
    "----- Mary joined the project team late, her supervisor is confident that she will fit right in.": {"anum": 3, "q_ja": "メアリーはプロジェクトチームに遅れて参加した----、上司は彼女がすぐに馴染むと確信している。", "a_ja": ["除いて", "にもかかわらず", "けれども", "しかしながら"]},
    "----- course you may take, you are sure to face many difficulties.": {"anum": 2, "q_ja": "----進路をとろうとも、多くの困難に直面することは確実だ。", "a_ja": ["どこでも", "どの", "どんなに", "いつでも"]},
    "The man speaks as if he ----- a native speaker of English.": {"anum": 3, "q_ja": "その男はまるで英語のネイティブスピーカー----ように話す。", "a_ja": ["だろう", "であった", "である", "である"]},
    "You can borrow this book ----- you return it to me by next Friday.": {"anum": 3, "q_ja": "来週の金曜日までに返してくれる----、この本を借りてもいいよ。", "a_ja": ["同様に", "同様に", "限り", "可能性が高い"]},
    "Some people say that the Internet is a passing fashion, ----- others believe it is a turning point in human history.": {"anum": 4, "q_ja": "インターネットは一時的な流行だと言う人もいれば、----人類史の転換点だと信じる人もいる。", "a_ja": ["考慮して", "判断すると", "間", "一方で"]},
    "If I had known you were here before I left home, I ----- your book with me.": {"anum": 4, "q_ja": "家を出る前にあなたがここにいると知っていたら、あなたの本を----のに。", "a_ja": ["持ってきた", "持ってきた", "持ってくる", "持ってきただろう"]},
    "If I had known the nature of the examination, I ----- the newspapers of the past several weeks more carefully.": {"anum": 2, "q_ja": "もし試験の性質を知っていたら、過去数週間の新聞をもっと注意深く----のに。", "a_ja": ["読んでいた", "読んだだろう", "読んだ", "読んでいた"]},
    "He has been in the hospital for two weeks.  That’s ----- he can’t come.": {"anum": 3, "q_ja": "彼は2週間入院している。それが彼が来られない----だ。", "a_ja": ["何", "いつ", "理由", "どう"]},
    "Had it not been for your help, I ----- my life in the attempt.": {"anum": 2, "q_ja": "あなたの助けがなかったら、私はその試みで命を----。", "a_ja": ["失うだろう", "失っていただろう", "失った", "失った"]},
    "This is the hospital ----- I was born.": {"anum": 3, "q_ja": "ここは私が生まれた病院だ。", "a_ja": ["その中で", "どちら", "そこで", "その中で"]},
    "That is the position for ----- Mr. Nagano has applied, but a final decision had not yet been made.": {"anum": 2, "q_ja": "それはナガノ氏が応募した職だが、最終決定はまだなされていない。", "a_ja": ["あれ", "（関係代名詞）", "何", "誰"]},
    "The main problem for me is ----- I am always sleepy.": {"anum": 3, "q_ja": "私にとっての主な問題は、いつも眠い----だ。", "a_ja": ["いつ", "何", "こと", "どちら"]},
    "If Robert ----- about the meeting, I’m sure he would have come.": {"anum": 1, "q_ja": "もしロバートが会議について----、彼はきっと来ただろう。", "a_ja": ["知っていたら", "知っている", "知った", "知っている"]},
    "Do you remember the house ----- you spent your childhood years?": {"anum": 2, "q_ja": "子供時代を過ごした家を覚えていますか？", "a_ja": ["どこ", "（関係代名詞）", "いつ", "誰"]},
    "Even the youngest boy ----- seemed to be enjoying the outing.": {"anum": 4, "q_ja": "私が話しかけた一番年下の男の子でさえ、遠足を楽しんでいるようだった。", "a_ja": ["彼らに話しかけた", "私が彼らに話しかけた", "私が話しかけた", "私が話しかけた"]},
    "The students wrote down the teacher’s e-mail address ----- they wouldn’t forget it.": {"anum": 2, "q_ja": "生徒たちは忘れない----、先生のメールアドレスを書き留めた。", "a_ja": ["万一", "ように", "限り", "これまでのところ"]},
    "He ----- won the election if it hadn’t been for the scandal.": {"anum": 4, "q_ja": "スキャンダルがなかったら、彼は選挙に----。", "a_ja": ["勝たない", "勝つ", "ありうる", "勝てただろう"]},
    "If you were to fall from that bridge, it ----- almost impossible to rescue you.": {"anum": 3, "q_ja": "もしあの橋から落ちたら、あなたを救助するのはほぼ不可能----。", "a_ja": ["だった", "だっただろう", "だろう", "である"]},
    "Susan is going to turn down John's offer. I would not do that if I ----- her.": {"anum": 1, "q_ja": "スーザンはジョンの申し出を断るつもりだ。もし私が彼女----、そんなことはしないだろう。", "a_ja": ["なら", "だろう", "だったなら", "だったなら"]},
    "You must not use the words ----- meanings you don’t understand well.": {"anum": 1, "q_ja": "意味をよく理解していない言葉を使ってはいけない。", "a_ja": ["その～", "どちら", "いつ", "誰"]},
    "If I were you, I ----- the report a few weeks in advance.": {"anum": 2, "q_ja": "もし私があなたなら、数週間前にレポートを----。", "a_ja": ["準備する", "準備するだろう", "準備する", "準備した"]},
    "His new TV drama is different from the previous ones in ----- it is based on a true incident.": {"anum": 2, "q_ja": "彼の新しいテレビドラマは、実話に基づいている----以前のものとは異なる。", "a_ja": ["何", "点において", "どちら", "場合"]},
    "“Was Jack at the party?\"  \"I don’t think so.  If he had been, I ----- him.”": {"anum": 2, "q_ja": "「ジャックはパーティーにいましたか？」「いなかったと思う。もしいたら、私は彼に----。」", "a_ja": ["会った", "会っていただろう", "会うだろう", "会った"]},
    "Relativity is a theory ----- many modern theories in physics are based.": {"anum": 4, "q_ja": "相対性理論は、物理学の多くの現代理論が基づいている理論だ。", "a_ja": ["その～", "それの", "あれ", "それの上に"]},
    "I wish it ----- rain here so much.": {"anum": 4, "q_ja": "ここではこんなに雨が----いいのに。", "a_ja": ["降らない", "降っていない", "降らない", "降らなければ"]},
    "If he ----- me about the deadline, I would have turned in the paper late.": {"anum": 2, "q_ja": "もし彼が締め切りについて私に----、私はレポートを遅れて提出していただろう。", "a_ja": ["思い出させない", "思い出させてくれなかったら", "思い出させられた", "思い出させない"]},
    "We are certain Roy would not have bought the machine if he ----- the reputation of that company.": {"anum": 4, "q_ja": "もしロイがその会社の評判を----、その機械を買わなかっただろうと私たちは確信している。", "a_ja": ["知った", "知っている", "知る", "知っていたら"]},
    "The police officer ----- works in our neighborhood is receiving an award today.": {"anum": 3, "q_ja": "私たちの近所で働いている警察官が今日表彰される。", "a_ja": ["誰", "どちら", "（関係代名詞）", "どこ"]},
    "As ----- as I know, he is the best soccer player in our class.": {"anum": 3, "q_ja": "私の知る----、彼はクラスで一番のサッカー選手だ。", "a_ja": ["長く", "良く", "限り", "すぐに"]},
    "Either you or I ----- supposed to organize a welcoming party for our new boss, but I’m just too busy right now.": {"anum": 3, "q_ja": "あなたか私のどちらかが新しい上司の歓迎会を企画することに----が、私は今とても忙しい。", "a_ja": ["なっている", "なる", "なっている", "なるだろう"]},
    "Please wait in this room ----- you are called.": {"anum": 2, "q_ja": "呼ばれる----この部屋でお待ちください。", "a_ja": ["なぜ", "まで", "～までに", "誰"]},
    "----- happens in the automobile market, the auto industry will not change its policies.": {"anum": 1, "q_ja": "自動車市場で----、自動車業界はその方針を変えないだろう。", "a_ja": ["何が起きようとも", "どんなに", "どこで", "いつでも"]},
    "Taro speaks English so fluently ----- he is taken for an American on the telephone.": {"anum": 1, "q_ja": "タロウはとても流暢に英語を話す----、電話ではアメリカ人と間違われる。", "a_ja": ["ので", "どちら", "～として", "もし"]},
    "There are several reasons ----- our family owns a second car.": {"anum": 3, "q_ja": "私たちの家族が2台目の車を所有しているのにはいくつかの----がある。", "a_ja": ["かどうか", "誰", "理由", "いつ"]},
    "There are a lot of students ----- have to work hard to pass the test.": {"anum": 4, "q_ja": "試験に合格するために一生懸命勉強しなければならない学生がたくさんいる。", "a_ja": ["その～", "いつ", "どちら", "（関係代名詞）"]},
    "On meeting at the welcoming reception, we felt as if we ----- each other for years.": {"anum": 1, "q_ja": "歓迎会で会った時、私たちはまるで何年も前からお互いを----ように感じた。", "a_ja": ["知っていた", "知っている", "知る", "知った"]},
    "A: I never have time to eat breakfast. B: Get up earlier, ----- you’ll have plenty of time.": {"anum": 1, "q_ja": "A: 朝食を食べる時間が全然ないんだ。 B: もっと早く起きなさい、----時間はたっぷりあるよ。", "a_ja": ["そうすれば", "しかし", "さもなければ", "～もまたない"]},
    "I like stories ----- have happy endings.": {"anum": 4, "q_ja": "私はハッピーエンドの物語が好きだ。", "a_ja": ["誰", "どこ", "何", "（関係代名詞）"]},
    "----- that you borrowed his car, he would be very angry.": {"anum": 4, "q_ja": "もしゴードンがあなたが彼の車を借りたことを----、彼はとても怒るだろう。", "a_ja": ["見つけたら", "見つけなければ", "見つける", "見つけたら"]},
    "This is the biggest ship ----- I have ever seen.": {"anum": 3, "q_ja": "これは私が今まで見た中で最も大きな船だ。", "a_ja": ["その～", "何", "（関係代名詞）", "誰"]},
    "I wonder if it ----- fine tomorrow.": {"anum": 2, "q_ja": "明日は晴れる----。", "a_ja": ["です", "だろうか", "だった", "ある"]},
    "The cook was ----- that we didn’t want to complain about the poor service.": {"anum": 1, "q_ja": "その料理人は----ので、私たちはひどいサービスについて文句を言いたくなかった。", "a_ja": ["とてもいい人だった", "とても親切な人", "とてもいい人", "とても親切な人"]},
    "If I had followed your advice, I ----- happier now.": {"anum": 4, "q_ja": "もしあなたのアドバイスに従っていたら、私は今もっと幸せ----。", "a_ja": ["だろう", "だった", "だ", "だろうに"]},
    "If it is fine tomorrow, we ----- fishing in the lake.": {"anum": 3, "q_ja": "明日晴れたら、私たちは湖に釣りに----。", "a_ja": ["行った", "行くだろう", "行くつもりだ", "行くだろう"]},
    "I could not have completed the task ----- your help.": {"anum": 4, "q_ja": "あなたの助け----、私はその仕事を完了できなかっただろう。", "a_ja": ["のおかげで", "にもかかわらず", "関係なく", "がなければ"]},
    "----- you sign up for our service, you can download any tune or show you want.": {"anum": 4, "q_ja": "私たちのサービスに登録----、好きな曲や番組をダウンロードできる。", "a_ja": ["どちらでも", "また", "どのように", "いったん～すれば"]},
    "There are often special box seats at sports stadiums, ----- people can watch games with food and drinks.": {"anum": 3, "q_ja": "スポーツスタジアムにはしばしば特別なボックス席があり、----人々は飲食しながら試合観戦ができる。", "a_ja": ["どちらでも", "どこでも", "そこで", "どちら"]},
    "Ghibli Museum is a place ----- I want to visit.": {"anum": 1, "q_ja": "ジブリ美術館は私が訪れたい場所だ。", "a_ja": ["（関係代名詞）", "どこ", "どこへ", "そこへ"]},
    "He bought the cheapest bike at the store, ----- left him with $10.": {"anum": 3, "q_ja": "彼は店で一番安い自転車を買ったが、----彼には10ドル残った。", "a_ja": ["ただ", "それによって", "それは", "それ"]},
    "This is the apartment house ----- my brother used to live.": {"anum": 3, "q_ja": "これは私の兄がかつて住んでいたアパートだ。", "a_ja": ["何", "いつ", "どこ", "どちら"]},
    "If you ----- any questions after the meeting, don't hesitate to e-mail me.": {"anum": 2, "q_ja": "会議後に質問が----、遠慮なくメールしてください。", "a_ja": ["あるだろう", "あれば", "あったら", "あった"]},
    "The man ----- John is talking is our math teacher.": {"anum": 4, "q_ja": "ジョンが話している男性は私たちの数学の先生だ。", "a_ja": ["いつ", "誰", "どこ", "誰と"]},
    "Let’s talk about some factors ----- caused the accident.": {"anum": 1, "q_ja": "事故を引き起こしたいくつかの要因について話しましょう。", "a_ja": ["（関係代名詞）", "その～", "どこ", "何"]},
    "If I had taken your advice before, I ----- in such trouble now.": {"anum": 1, "q_ja": "以前あなたのアドバイスを聞いていたら、今こんなトラブルには----。", "a_ja": ["なっていないだろう", "なっていない", "なっているだろう", "なっていただろう"]},
    "Nowadays no ----- where you are, you have access to the Internet.": {"anum": 2, "q_ja": "今日では、どこにいても----インターネットにアクセスできる。", "a_ja": ["不思議", "関係なく", "感謝", "長く"]},
    "The mother said in a loud voice, “It’s time -----.”": {"anum": 4, "q_ja": "母親は大声で言った。「もう----時間よ。」", "a_ja": ["寝なければならない", "寝るだろう", "寝てしまった", "寝る"]},
    "I wish I ----- another foreign language in my college days.": {"anum": 3, "q_ja": "大学時代にもう一つの外国語を----よかったのに。", "a_ja": ["学ぶ", "学んだだろう", "学んでおけば", "学ぶべき"]},
    "It is time we ----- packing. We only have two hours left before we leave.": {"anum": 2, "q_ja": "もう荷造りを----時間だ。出発まであと2時間しかない。", "a_ja": ["始める", "始めた", "始めるだろう", "始めている"]},
    "Mr. Bell is the person ----- I obtained the information.": {"anum": 4, "q_ja": "ベル氏は私が情報を得た相手だ。", "a_ja": ["誰に", "何のために", "誰の", "誰から"]},
    "A: Thank you for your email about the party for Nancy. B: Can you make it? A: -----. B: That's too bad.": {"anum": 4, "q_ja": "A: ナンシーのパーティーについてのメールありがとう。 B: 来られる？ A: ----。 B: それは残念だね。", "a_ja": ["行かなければよかった", "彼女にチョコケーキを作りたい", "彼女に会うのが待ちきれない", "残念ながら行けない"]},
    "What kind of person do you think you could have been if you ----- a musician?": {"anum": 4, "q_ja": "もしミュージシャンに----、どんな人間になっていたと思いますか？", "a_ja": ["なっていなかった", "なるべきでなかった", "ならないだろう", "なっていなかったら"]},
    "----- seems easy at first often turns out to be difficult.": {"anum": 1, "q_ja": "最初は簡単に見える----が、後で難しいとわかることがよくある。", "a_ja": ["こと", "なぜ", "どちら", "あれ"]},
    "The man ----- I believed was one of the executives turned out to be a part-time worker.": {"anum": 4, "q_ja": "私が幹部の一人だと信じていた男性は、アルバイトだと判明した。", "a_ja": ["どちら", "何", "その～", "（関係代名詞）"]},
    "If I had left earlier, I ----- the rain.": {"anum": 2, "q_ja": "もっと早く出発していたら、雨を----。", "a_ja": ["避けられる", "避けられたのに", "避けた", "避けるだろう"]},
    "His mother continued talking as if nothing -----.": {"anum": 3, "q_ja": "彼の母親はまるで何も----かのように話し続けた。", "a_ja": ["起こるだろう", "起こった", "起こらなかった", "起こるだろう"]},
    "My father gave me the money. -----, I couldn't have afforded the trip.": {"anum": 1, "q_ja": "父が私にお金をくれた。----、私はその旅行に行く余裕がなかっただろう。", "a_ja": ["さもなければ", "このために", "それにもかかわらず", "したがって"]},
    "If you have a good luck, you ----- a nice view of Mt. Fuji.": {"anum": 3, "q_ja": "運が良ければ、富士山の素晴らしい景色が----。", "a_ja": ["あった", "あっただろう", "見られるだろう", "見られただろう"]},
    "If I ----- you, I wouldn’t have done such a thing.": {"anum": 3, "q_ja": "もし私があなた----、そんなことはしなかっただろう。", "a_ja": ["だった", "である", "なら", "だったなら"]},
    "----- further information is available so far, but we are expecting an update within 24 hours.": {"anum": 2, "q_ja": "これまでのところ詳細な情報は----が、24時間以内の更新を期待している。", "a_ja": ["どんな", "ない", "多くの", "ほとんどない"]},
    "Mozart could not live life without making music. Life without music ----- meaningless to him.": {"anum": 3, "q_ja": "モーツァルトは音楽を作らずには生きられなかった。音楽のない人生は彼にとって無意味----。", "a_ja": ["だった可能性がある", "だっただろう", "だったに違いない", "である必要はない"]},
    "He acted as if his life ----- over.": {"anum": 1, "q_ja": "彼はまるで人生が終わった----ように振る舞った。", "a_ja": ["か", "だろう", "だろう", "である"]},
    "----- my body feels fine, mentally I am very tired.": {"anum": 1, "q_ja": "体は元気だ----、精神的にはとても疲れている。", "a_ja": ["が", "にもかかわらず", "～するために", "にもかかわらず"]},
    "The famous painter, ----- picture had been sold for ten thousand dollars, visited Japan in 2003.": {"anum": 3, "q_ja": "その絵が1万ドルで売れた有名な画家が、2003年に来日した。", "a_ja": ["誰", "誰の", "その～", "誰と"]},
    "These are the tools ----- he built his own house.": {"anum": 2, "q_ja": "これらは彼が自分の家を建てた道具だ。", "a_ja": ["あれ", "それを使って", "どちら", "それを使って"]},
    "Even if I had gone, there was ----- chance that I would have been able to meet them anyway.": {"anum": 3, "q_ja": "たとえ私が行っていたとしても、いずれにせよ彼らに会えた可能性は----。", "a_ja": ["ほとんどない", "ほとんどない", "ほとんどない", "ほとんどない"]},
    "If our last batter had not hit a home run, our team ----- the game.": {"anum": 4, "q_ja": "もし最後の打者がホームランを打っていなかったら、私たちのチームは試合に----。", "a_ja": ["勝つだろう", "負けるだろう", "勝っていただろう", "負けていただろう"]},
    "She looked ----- she had heard some bad news.": {"anum": 2, "q_ja": "彼女はまるで悪い知らせを聞いた----に見えた。", "a_ja": ["～で", "かのように", "そして", "けれども"]},
    "She performs the folk songs not only through sign language ----- through her steps and body movements.": {"anum": 4, "q_ja": "彼女は手話だけでなく、ステップや体の動きを通じても民謡を演じる。", "a_ja": ["～として", "そして", "だから", "しかしまた"]},
    "If you had taken my advice, you ----- more successful at that time.": {"anum": 4, "q_ja": "もし私のアドバイスを聞いていたら、その時あなたはもっと成功----。", "a_ja": ["していただろう", "するだろう", "している", "していただろう"]},
    "----- uncomfortable you may be, you are required to wear protective clothes in this laboratory.": {"anum": 2, "q_ja": "どんなに不快----、この実験室では防護服を着用しなければならない。", "a_ja": ["けれども", "であっても", "にもかかわらず", "なぜなら"]},
    "I’ve already read the book ----- she lent to me.": {"anum": 1, "q_ja": "彼女が貸してくれた本はもう読んだ。", "a_ja": ["（関係代名詞）", "何", "誰", "その～"]},
    "If you ----- me what was going on, I would have told you the whole story.": {"anum": 1, "q_ja": "もし何が起きているのか私に----、私はあなたに全てを話しただろう。", "a_ja": ["聞いていたら", "聞いていたら", "聞いた", "聞くなら"]},
    "He hardly ----- misses a meeting.": {"anum": 2, "q_ja": "彼は会議を欠席することは----。", "a_ja": ["もまたない", "めったにない", "決してない", "どちらも"]},
    "Listening to music helps some people focus ----- they study.": {"anum": 2, "q_ja": "音楽を聴くことは、勉強している----集中するのに役立つ人もいる。", "a_ja": ["何", "間", "間", "～について"]},
    "People should be aware ----- natural resources are limited.": {"anum": 3, "q_ja": "人々は天然資源に限りがある----気づくべきだ。", "a_ja": ["ように", "について", "ことに", "～の"]},
    "There was ----- hope of finding the missing report.": {"anum": 4, "q_ja": "紛失した報告書が見つかる見込みは----。", "a_ja": ["めったにない", "ほとんどない", "ほとんどない", "ほとんどない"]},
    "The group is working to preserve old buildings that could ----- be lost.": {"anum": 3, "q_ja": "そのグループは、さもなければ失われてしまうかもしれない古い建物の保存に取り組んでいる。", "a_ja": ["めったに", "同様に", "さもなければ", "ほとんど"]},
    "Where’s the magazine ----- you bought the other day.": {"anum": 1, "q_ja": "先日あなたが買った雑誌はどこ？", "a_ja": ["（関係代名詞）", "どこ", "誰", "誰"]},
    "If I were rich, I ----- around the world.": {"anum": 1, "q_ja": "もし金持ちなら、世界中を----。", "a_ja": ["旅行するだろう", "旅行するつもりだ", "旅行できる", "旅行できただろう"]},
    "I wish I ----- a brother.": {"anum": 2, "q_ja": "兄弟が----いいのに。", "a_ja": ["いる", "いれば", "いるだろう", "いた"]},
    "Professor Sands is angry with you for being late again. If I were you, I ----- to him.": {"anum": 1, "q_ja": "サンズ教授はまた遅刻したことであなたに怒っている。もし私があなたなら、彼に----。", "a_ja": ["謝るだろう", "謝った", "謝っていただろう", "謝るつもりだ"]},
    "If I had known you were already here waiting, I ----- earlier.": {"anum": 1, "q_ja": "あなたがすでにここで待っていると知っていたら、もっと早く----。", "a_ja": ["来ただろう", "来た", "来るつもりだ", "来られなかった"]},
    "Last winter I went to Hong Kong, ----- it wasn’t as warm as I had expected.": {"anum": 2, "q_ja": "去年の冬香港に行ったが、期待していたほど暖かくなかった。", "a_ja": ["何", "そこで", "どちら", "いつ"]},
    "I’m going to spend two weeks in New York, ----- my brother lives.": {"anum": 3, "q_ja": "私はニューヨークで2週間過ごすつもりだ。そこには兄が住んでいる。", "a_ja": ["何", "どちら", "そこで", "その～"]},
    "When I was a child, the man treated me as if I ----- his own daughter.": {"anum": 4, "q_ja": "子供の頃、その男性はまるで私が彼の実の娘----ように私を扱った。", "a_ja": ["である", "であった", "だろう", "である"]},
    "You'll never know ----- you try.": {"anum": 1, "q_ja": "やってみ----、決してわからないだろう。", "a_ja": ["ない限り", "いつ", "あれ", "後"]},
    "----- you find something wrong, make sure to contact me immediately.": {"anum": 4, "q_ja": "万一何か問題が見つかったら、すぐに私に連絡してください。", "a_ja": ["～だろう", "～できた", "～かもしれない", "万一"]},
    "Foreign language education combines the fields of ----- science and art.": {"anum": 3, "q_ja": "外国語教育は科学と芸術の----分野を組み合わせている。", "a_ja": ["間", "どちらも～ない", "両方の", "どちらか"]},
    "Charlie Chaplin was an actor ----- was best known for his work in silent movies.": {"anum": 3, "q_ja": "チャーリー・チャップリンはサイレント映画での活躍で最もよく知られた俳優だった。", "a_ja": ["何", "その～", "（関係代名詞）", "どちら"]},
    "The girl ----- talking to this morning is from Canada.": {"anum": 1, "q_ja": "今朝私が話していた女の子はカナダ出身だ。", "a_ja": ["私が", "私が", "誰が", "私が"]},
    "She has a son, ----- is a college student.": {"anum": 1, "q_ja": "彼女には息子がいて、彼は大学生だ。", "a_ja": ["そして彼は", "何", "誰", "あれ"]},
    "Last night the old woman forgot to shut the windows in the living room, ----- she usually does.": {"anum": 3, "q_ja": "昨夜、その老婦人は居間の窓を閉めるのを忘れたが、それは彼女が普段していることだ。", "a_ja": ["いつ", "あれ", "それは", "何"]},
    "If Morley ----- a life jacket, he might have drowned in the river.": {"anum": 1, "q_ja": "もしモーリーがライフジャケットを----、彼は川で溺れていたかもしれない。", "a_ja": ["着ていなかったら", "着ていない", "着ていなかった", "着ていなかったら"]},
    "There are numerous cases ----- Japanese modesty causes misunderstanding.": {"anum": 4, "q_ja": "日本人の謙虚さが誤解を招くケースは数多くある。", "a_ja": ["どちら", "あれ", "何", "そこでは"]},
    "I cannot speak English at all. I wish I ----- speak it well.": {"anum": 2, "q_ja": "私は英語が全く話せない。上手に----いいのに。", "a_ja": ["話さなければならない", "話せれば", "話せる", "話してもよい"]},
    "----- I become a university student, I will have grown four more inches.": {"anum": 3, "q_ja": "大学生になる----、私はあと4インチ背が伸びているだろう。", "a_ja": ["まで", "たとえ～でも", "頃には", "限り"]},
    "What would you do if you ----- a suitcase full of money?": {"anum": 4, "q_ja": "もしお金の詰まったスーツケースを----、どうしますか？", "a_ja": ["見つけたら", "見つける", "見つけたら", "見つけたら"]},
    "You should know that a lower price doesn’t ----- mean lower quality.": {"anum": 1, "q_ja": "価格が安いからといって、----品質が低いわけではないことを知っておくべきだ。", "a_ja": ["必ずしも", "必要性", "必要な", "必要"]},
    "This is ----- Mr. Jobs succeeded in the personal computer business.": {"anum": 4, "q_ja": "これがジョブズ氏がパソコンビジネスで成功した----だ。", "a_ja": ["どちら", "何", "方法", "方法"]},
    "I bought plastic cups for the party, so they won't break ----- the children drop them.": {"anum": 2, "q_ja": "パーティー用にプラスチックのコップを買ったので、子供たちが落とし----割れない。", "a_ja": ["けれども", "ても", "にもかかわらず", "まだ"]},
    "She claimed strongly ----- she had never said such a stupid thing.": {"anum": 3, "q_ja": "彼女はそんな馬鹿なことは一度も言っていないと強く主張した。", "a_ja": ["誰", "どちら", "と", "何"]},
    "Around two billion children live in places ----- pollution levels are too high.": {"anum": 4, "q_ja": "約20億人の子供たちが、汚染レベルが高すぎる場所に住んでいる。", "a_ja": ["その中で", "どちら", "何", "そこでは"]},
    "He talks as if he ----- everything.": {"anum": 1, "q_ja": "彼はまるで全てを----かのように話す。", "a_ja": ["知っている", "知っている", "知った", "知るだろう"]},
    "We should not dismiss these ideas just ----- they are unfamiliar.": {"anum": 4, "q_ja": "馴染みがないからといって、これらのアイデアを却下すべきではない。", "a_ja": ["～として", "～のために", "～以来", "～だから"]},
    "If you had come ten minutes earlier, you ----- her.": {"anum": 2, "q_ja": "もし10分早く来ていたら、彼女に----。", "a_ja": ["会うだろう", "会えたのに", "会えた", "会った"]},
    "If I ----- a little younger, I would join you in climbing the mountain.": {"anum": 3, "q_ja": "もしもう少し若----、あなたと一緒に山に登るのに。", "a_ja": ["だった", "だった", "ければ", "である"]},
    "Even if the sun ----- rise in the west, he would never stop loving his wife.": {"anum": 1, "q_ja": "たとえ太陽が西から昇るようなことが----、彼は妻を愛するのをやめないだろう。", "a_ja": ["あっても", "あった", "ある", "かもしれない"]},
    "It was raining, ----- they went out for hiking.": {"anum": 4, "q_ja": "雨が降っていた----、彼らはハイキングに出かけた。", "a_ja": ["むしろ", "なぜなら", "にもかかわらず", "が"]},
    "You may have ----- soup or salad with your dinner.": {"anum": 3, "q_ja": "夕食にスープかサラダの----をとることができる。", "a_ja": ["両方", "どちらも～ない", "どちらか", "選択"]},
    "----- he told me was a lie.": {"anum": 3, "q_ja": "彼が私に言った----は嘘だった。", "a_ja": ["あれ", "いつ", "こと", "どこ"]},
    "I feel hungry now. I wish I ----- something before I left home.": {"anum": 2, "q_ja": "今お腹が空いている。家を出る前に何か----よかったのに。", "a_ja": ["食べていなければ", "食べておけば", "食べた", "食べた"]},
    "----- your timely advice, I would have failed to deal with this matter.": {"anum": 4, "q_ja": "あなたのタイムリーな助言----、私はこの問題に対処し損なっていただろう。", "a_ja": ["にもかかわらず", "～は別として", "～の代わりに", "がなければ"]},
    "He was annoyed by hotels ----- made guests pay for web access.": {"anum": 2, "q_ja": "彼はウェブアクセスに料金を請求するホテルにうんざりしていた。", "a_ja": ["どこ", "（関係代名詞）", "誰", "いつ"]},
    "Wait ----- you get home before you open this gift box.": {"anum": 4, "q_ja": "家に帰る----このギフトボックスを開けるのを待ちなさい。", "a_ja": ["～へ", "いつ", "後", "まで"]},
    "If I ----- her advice at that time, I might be out of work now.": {"anum": 1, "q_ja": "もしあの時彼女のアドバイスを----、私は今失業しているかもしれない。", "a_ja": ["受け入れていなかったら", "受け入れていない", "受け入れない", "受け入れないだろう"]},
    "Thank you, Hiromi.  This book is exactly ----- I wanted.": {"anum": 1, "q_ja": "ありがとう、ヒロミ。この本はまさに私が欲しかった----だ。", "a_ja": ["もの", "あれ", "その～", "どちら"]},
    "I have a friend ----- father is a lawyer.": {"anum": 4, "q_ja": "私には父親が弁護士である友人がいる。", "a_ja": ["誰", "誰", "どちら", "その～"]},
    "I have a friend ----- wants to be an astronaut.": {"anum": 2, "q_ja": "私には宇宙飛行士になりたい友人がいる。", "a_ja": ["その～", "（関係代名詞）", "誰", "どちら"]},
    "John ----- the team if he had time, but he is really busy now.": {"anum": 3, "q_ja": "もし時間があればジョンはチームに----が、彼は今本当に忙しい。", "a_ja": ["参加する", "参加した", "参加するだろう", "参加した"]},
    "A report ----- the area was dangerous was ignored by the residents.": {"anum": 2, "q_ja": "その地域が危険である----報告は住民に無視された。", "a_ja": ["何", "という", "関する", "どちら"]},
    "He didn’t cry, ----- was very brave on his part.": {"anum": 1, "q_ja": "彼は泣かなかった。----は彼にしてはとても勇敢だった。", "a_ja": ["それ", "何", "どこ", "誰"]},
    "The dress ----- Ann bought is so cute.": {"anum": 2, "q_ja": "アンが買ったドレスはとてもかわいい。", "a_ja": ["その～", "（関係代名詞）", "いつ", "誰"]},
    "You must not forget that all ----- glitters is not gold.": {"anum": 4, "q_ja": "輝くものすべてが金ではないことを忘れてはならない。", "a_ja": ["その～", "どちら", "それ", "（関係代名詞）"]},
    "It is getting dark, and ----- was worse, it began to snow.": {"anum": 4, "q_ja": "暗くなり、----悪いことに、雪が降り始めた。", "a_ja": ["どこ", "どう", "～として", "さらに"]},
    "----- I want you to think about for a moment is what happens after you do it.": {"anum": 3, "q_ja": "あなたに少し考えてほしい----は、それをした後に何が起こるかだ。", "a_ja": ["いつ", "どう", "こと", "なぜ"]},
    "I wish you ----- everything about John before I talked to him.": {"anum": 1, "q_ja": "私がジョンと話す前に、彼についての全てを----よかったのに。", "a_ja": ["話してくれれば", "話してくれる", "話した", "知らせる"]},
    "Look at the boy and his dog ----- are walking over there.": {"anum": 4, "q_ja": "あそこを歩いている少年と犬を見なさい。", "a_ja": ["どこ", "その～", "何", "（関係代名詞）"]},
    "She asked me ----- I could wait for her until she came back.": {"anum": 1, "q_ja": "彼女は戻ってくるまで待てる----私に尋ねた。", "a_ja": ["かどうか", "後", "あれ", "そこ"]},
    "If I ----- to be the sales manager, I would definitely promote this new product.": {"anum": 3, "q_ja": "もし私が営業部長に----、間違いなくこの新製品を宣伝するだろう。", "a_ja": ["選ぶ", "選んでいた", "選ばれたら", "選んだ"]},
    "I didn’t like ----- the man talked.": {"anum": 2, "q_ja": "私はその男の話し----が好きではなかった。", "a_ja": ["いつ", "方", "どちら", "どこ"]},
    "How monotonous our life would be, if it ----- not for the changes of the season.": {"anum": 3, "q_ja": "もし季節の移り変わりが----、私たちの生活はなんと単調なことだろう。", "a_ja": ["かもしれない", "すべき", "なければ", "ある"]},
    "If I ----- at the station five minutes earlier, I could have caught the train.": {"anum": 3, "q_ja": "もし5分早く駅に----、電車に乗れたのに。", "a_ja": ["着いたら", "着いた", "着いていたら", "着いている"]},
    "----- the traffic accident, we would have arrived earlier.": {"anum": 3, "q_ja": "交通事故----、私たちはもっと早く着いていただろう。", "a_ja": ["同様に", "ただ～だけ", "がなければ", "～から"]},
    "A large portion of ----- the Japanese eat every day is imported from other countries.": {"anum": 3, "q_ja": "日本人が毎日食べる----の大部分は他国から輸入されている。", "a_ja": ["誰", "どちら", "もの", "あれ"]},
    "Timothy was greeted with a series of questions ----- he had no answers.": {"anum": 1, "q_ja": "ティモシーは彼が答えられない一連の質問攻めにあった。", "a_ja": ["それに対して", "あれ", "どちら", "それによって"]},
    "Please show me ----- you have in your hands.": {"anum": 3, "q_ja": "あなたが手に持っている----を見せてください。", "a_ja": ["どちら", "あれ", "もの", "どこ"]},
    "The firemen had trouble getting to the street ----- the houses were on fire.": {"anum": 4, "q_ja": "消防士たちは家が燃えている通りにたどり着くのに苦労した。", "a_ja": ["どちら", "あれ", "どう", "そこでは"]},
    "At this point, Shannon wished she ----- mechanical drawing. She hated the course.": {"anum": 1, "q_ja": "この時点で、シャノンは製図を----よかったと思った。彼女はそのコースが嫌いだった。", "a_ja": ["取らなければ", "取るなら", "取った", "取らないだろう"]},
    "This is a photo ----- was taken 100 years ago.": {"anum": 2, "q_ja": "これは100年前に撮られた写真だ。", "a_ja": ["どこ", "（関係代名詞）", "いつ", "何"]},
    "I met a girl ----- mother is a well-known astronomer.": {"anum": 1, "q_ja": "私は母親が有名な天文学者である少女に会った。", "a_ja": ["その～", "誰", "誰", "どちら"]},
    "If the train had not been late, I ----- in time for the concert yesterday.": {"anum": 2, "q_ja": "もし電車が遅れていなかったら、昨日のコンサートに----。", "a_ja": ["間に合わなかっただろう", "間に合っただろう", "間に合わないだろう", "間に合うだろう"]},
    "Jack ----- misses an opportunity to play in the badminton tournaments.": {"anum": 1, "q_ja": "ジャックはバドミントンの大会に出る機会を----逃さない。", "a_ja": ["めったに～ない", "めったに～ない", "めったに～ない", "めったに～ない"]},
    "The teacher ----- teaches us English comes from Canada.": {"anum": 4, "q_ja": "私たちに英語を教えている先生はカナダ出身だ。", "a_ja": ["どちら", "その～", "誰", "（関係代名詞）"]},
    "It's been quite a while ----- we saw each other.": {"anum": 4, "q_ja": "私たちが会って----かなり経つ。", "a_ja": ["なぜなら", "けれども", "あれ", "から"]},
    "----- coffee or tea is fine with me.": {"anum": 3, "q_ja": "コーヒーか紅茶の----私には構わない。", "a_ja": ["両方", "～かどうか", "どちらでも", "どちらも～ない"]},
    "The era will soon come ----- what scientists are saying will come true.": {"anum": 1, "q_ja": "科学者たちが言っていることが実現する時代がすぐに来るだろう。", "a_ja": ["いつ", "～へ", "どちら", "どこ"]},
    "That is the position for ----- Mr. Kato has applied, but a final decision has not been made.": {"anum": 1, "q_ja": "それはカトウ氏が応募した職だが、最終決定はまだなされていない。", "a_ja": ["（関係代名詞）", "何", "あれ", "誰"]},
    "Christmas is the day ----- the whole family gets together.": {"anum": 4, "q_ja": "クリスマスは家族全員が集まる日だ。", "a_ja": ["その～", "あれ", "何", "いつ"]},
    "----- created this program is a genius.": {"anum": 3, "q_ja": "このプログラムを作った----は天才だ。", "a_ja": ["誰でも", "何", "人は誰でも", "誰"]},
    "----- you have any problem regarding our products, please feel free to contact us.": {"anum": 1, "q_ja": "万一当社の製品に関して問題が----、お気軽にご連絡ください。", "a_ja": ["あれば", "～だろう", "～かもしれない", "～できた"]},
    "If it -----, let’s go hiking tomorrow.": {"anum": 2, "q_ja": "もし----、明日ハイキングに行こう。", "a_ja": ["雨が降らないだろう", "雨が降らなければ", "雨が降っていなかったら", "雨が降らなかった"]},
    "----- birds, the world would be filled with insects.": {"anum": 1, "q_ja": "もし鳥が----、世界は昆虫でいっぱいになるだろう。", "a_ja": ["いなければ", "いれば", "いなかったら", "いたら"]},
    "I visited the website of an Italian food shop, ----- I ordered an excellent olive oil.": {"anum": 3, "q_ja": "私はイタリア食品店のウェブサイトを訪れ、----素晴らしいオリーブオイルを注文した。", "a_ja": ["どちら", "いつ", "そこで", "何"]},
    "If he had lived one day longer, he ----- one hundred years old.": {"anum": 4, "q_ja": "もし彼があと1日長く生きていたら、彼は100歳に----。", "a_ja": ["なっていただろう", "なる", "なっていただろう", "なっていただろう"]},
    "If I ----- his telephone number, I would call him.": {"anum": 2, "q_ja": "もし彼の電話番号を----、彼に電話するのに。", "a_ja": ["知ることができれば", "知っていれば", "知っている", "知っていたら"]},
    "If I ----- him earlier, my life would have been different.": {"anum": 3, "q_ja": "もしもっと早く彼に----、私の人生は違っていただろう。", "a_ja": ["会った", "会う", "会っていたら", "会った"]},
    "----- I go to Hawaii, I always stay at the same hotel.": {"anum": 3, "q_ja": "ハワイに行く----、いつも同じホテルに泊まる。", "a_ja": ["どちらへ", "何でも", "時はいつでも", "どこへ"]},
    "This is the book ----- I told you yesterday.": {"anum": 3, "q_ja": "これが昨日あなたに話した本だ。", "a_ja": ["その～", "どこ", "それについて", "何"]},
    "She would like to live in a county ----- it never snows.": {"anum": 3, "q_ja": "彼女は雪が全く降らない郡に住みたいと思っている。", "a_ja": ["その～", "誰", "そこでは", "どちら"]},
    "I was standing there lost in thought ----- I was called from behind.": {"anum": 2, "q_ja": "考え事をしてそこに立っていた----、後ろから声をかけられた。", "a_ja": ["もし", "時", "誰", "誰"]},
    "If he ----- his money in stocks, he would be a millionaire now.": {"anum": 1, "q_ja": "もし彼がお金を株に----、彼は今頃億万長者だろう。", "a_ja": ["投資していたら", "投資した", "投資した", "投資する"]},
    "The woman ----- we saw in the park was Aya’s sister.": {"anum": 1, "q_ja": "私たちが公園で見かけた女性はアヤの姉だった。", "a_ja": ["（関係代名詞）", "どちら", "その～", "いつ"]},
    "That was the reason ----- stopped them from moving to the city.": {"anum": 2, "q_ja": "それが彼らが都市へ引っ越すのをやめた理由だった。", "a_ja": ["なぜなら", "（関係代名詞）", "～のために", "なぜ"]},
    "The coach said that ----- practiced hard.": {"anum": 4, "q_ja": "コーチは、----一生懸命練習したわけではないと言った。", "a_ja": ["全ての選手が～ない", "全ての～ない選手が", "～ない全ての選手が", "全ての選手が～というわけではない"]},
    "If you ----- at ten tomorrow, the president will meet you.": {"anum": 4, "q_ja": "もし明日10時に----、社長があなたに会います。", "a_ja": ["来るだろう", "来た", "来ていたら", "来れば"]},
    "There was a horrible picture of a man ----- leg had been blown off.": {"anum": 4, "q_ja": "足を吹き飛ばされた男の恐ろしい写真があった。", "a_ja": ["あれ", "どちら", "誰", "その～"]},
    "I ----- do that if I were you.": {"anum": 3, "q_ja": "もし私があなたなら、そんなことは----。", "a_ja": ["しない", "できない", "しないだろう", "しないだろう"]},
    "Lisa will marry ----- she believes is reliable.": {"anum": 4, "q_ja": "リサは彼女が信頼できると信じる----と結婚するだろう。", "a_ja": ["何でも", "どんなに", "いつでも", "人は誰でも"]},
    "If I had known about the defect of the product, I ----- buying it.": {"anum": 4, "q_ja": "もし製品の欠陥について知っていたら、それを買うのを----。", "a_ja": ["避けるだろう", "避けるつもりだ", "避けた", "避けていただろう"]},
    "I would be really surprised if he ----- elected mayor next year.": {"anum": 1, "q_ja": "もし彼が来年市長に選ばれ----、私は本当に驚くだろう。", "a_ja": ["たら", "たら", "たら", "たら"]},
    "Discounted season passes are now available to fans ----- want to see a large number of events at the Sapporo Dome.": {"anum": 4, "q_ja": "札幌ドームで多くのイベントを見たいファンには、割引シーズンパスが現在利用可能だ。", "a_ja": ["どこ", "いつ", "何", "（関係代名詞）"]},
    "What would Kate do if she ----- truth?": {"anum": 4, "q_ja": "もしケイトが真実を----、どうするだろうか？", "a_ja": ["知ることができる", "知っている", "知るだろう", "知っていたら"]},
    "If it ----- tomorrow, I would stay at home.": {"anum": 1, "q_ja": "万一明日雪が----、私は家にいるだろう。", "a_ja": ["降れば", "降るだろう", "降る", "降る"]},
    "Do you remember the teacher ----- daughter became an attorney?": {"anum": 2, "q_ja": "娘が弁護士になった先生を覚えていますか？", "a_ja": ["誰", "その～", "どちら", "あれ"]},
    "I wish it ----- raining soon so we could start our game again.": {"anum": 3, "q_ja": "また試合を始められるように、すぐに雨が----いいのに。", "a_ja": ["止むだろう", "止んだ", "止んでくれれば", "止んでいた"]},
    "If you ----- get lost in town, use this mobile phone.": {"anum": 4, "q_ja": "万一町で迷ったら、この携帯電話を使いなさい。", "a_ja": ["～だろう", "～だろう", "～できた", "万一"]},
    "----- the sun rises in the east, Japan has long been called the land of the rising sun.": {"anum": 2, "q_ja": "太陽は東から昇る----、日本は長い間日出ずる国と呼ばれてきた。", "a_ja": ["～のために", "ので", "いつ", "もし"]},
    "They’ve ----- eaten anything. Aren’t they hungry?": {"anum": 4, "q_ja": "彼らは----何も食べていない。お腹が空いていないのだろうか？", "a_ja": ["ほとんど", "少し", "し損なった", "ほとんど～ない"]},
    "If I ----- a camera, I could have taken some beautiful pictures.": {"anum": 2, "q_ja": "もしカメラを----、美しい写真が撮れたのに。", "a_ja": ["持っている", "持っていたら", "持っていた", "持っていれば"]},
    "I wish I ----- you when I was in high school.": {"anum": 3, "q_ja": "高校生の時にあなたを----よかったのに。", "a_ja": ["知っていた", "知っている", "知っていたら", "知っている"]},
    "It will not be long ----- she becomes a professional golf player.": {"anum": 2, "q_ja": "彼女がプロゴルファーになるまで----だろう。", "a_ja": ["すぐに", "まもなく", "間", "最近"]},
    "Without American influences, Japanese culture would not be ----- it is today.": {"anum": 1, "q_ja": "アメリカの影響がなければ、日本文化は今日の----ではないだろう。", "a_ja": ["姿", "どちら", "いつ", "あれ"]},
    "My mother asked me ----- I wanted to go shopping with her or not.": {"anum": 1, "q_ja": "母は私に一緒に買い物に行きたい----尋ねた。", "a_ja": ["かどうか", "いつ", "なぜ", "何"]},
    "I am sorry to hear that you didn't win the game. If ----- you had practiced harder.": {"anum": 3, "q_ja": "試合に勝てなかったと聞いて残念だ。もっと一生懸命練習して----よかったのに。", "a_ja": ["必要", "かつて", "さえいれば", "あれ"]},
    "“Smartphone” is a word ----- we are all familiar.": {"anum": 2, "q_ja": "「スマートフォン」は私たち全員がよく知っている言葉だ。", "a_ja": ["その中で", "それに", "そのために", "それの"]},
}

process_file('glammer-2B.csv', data)
