from process_csv import process_file

data = {
    "Religion is a ----- issue.": {"anum": 1, "q_ja": "宗教は----な問題だ。", "a_ja": ["敏感な、デリケートな", "尊敬", "独創的な", "正直な"]},
    "Good ----- is expected of students in school.": {"anum": 1, "q_ja": "学校では学生に良い----が期待される。", "a_ja": ["行い、行為", "納得させる", "優しい", "出席する"]},
    "That blouse doesn't ----- your skirt.": {"anum": 3, "q_ja": "そのブラウスはあなたのスカートに----ない。", "a_ja": ["口論する", "感謝する", "調和する、合う", "競争"]},
    "We must ----- the environment from pollution.": {"anum": 4, "q_ja": "私たちは環境を汚染から----なければならない。", "a_ja": ["生き残る", "抗議する", "存在する", "保護する"]},
    "She was ----- with her child's behavior.": {"anum": 3, "q_ja": "彼女は子供の振る舞いに----をした。", "a_ja": ["許した", "引き起こした", "恥ずかしい思いをさせる", "閉じた"]},
    "I ----- your lending me this interesting book.": {"anum": 1, "q_ja": "この面白い本を貸してくれて----します。", "a_ja": ["感謝する", "許す", "扱う", "調和する"]},
    "She suddenly burst into ----- and ran out.": {"anum": 1, "q_ja": "彼女は突然----を出して走り去った。", "a_ja": ["涙", "恥ずかしい思いをさせる", "天国", "風"]},
    "I ----- if her story is true.": {"anum": 1, "q_ja": "彼女の話は本当----。", "a_ja": ["～かなと思う", "リラックスする", "反応する", "受け入れる"]},
    "Could you wait a -----, please?": {"anum": 2, "q_ja": "----お待ちいただけますか？", "a_ja": ["後者の", "瞬間、ちょっとの間", "さらなる", "前者の"]},
    "Firefighters ----- people from the burning building.": {"anum": 1, "q_ja": "消防士たちは燃えている建物から人々を----した。", "a_ja": ["救助する", "維持する", "逃げる", "生き残る"]},
    "This is the most ----- restaurant in my town.": {"anum": 2, "q_ja": "これは私の町で最も----なレストランだ。", "a_ja": ["価格", "高価な", "費用", "価値"]},
    "Go straight ----- and you'll get to the main street.": {"anum": 4, "q_ja": "まっすぐ----へ進めば大通りに出ます。", "a_ja": ["以前の", "前者の", "次の", "前方へ"]},
    "He ----- Susan for her hard work.": {"anum": 3, "q_ja": "彼はスーザンの勤勉さを----した。", "a_ja": ["納得させる", "頼る", "称賛する", "混ぜる"]},
    "The ----- about the professor made everybody laugh.": {"anum": 1, "q_ja": "教授についての----は皆を笑わせた。", "a_ja": ["冗談", "起源", "根", "愚かな"]},
    "I've got ----- recently.": {"anum": 4, "q_ja": "私は最近----った。", "a_ja": ["前方へ", "重さがある", "高さ", "太った"]},
    "The mother is very ----- with her baby.": {"anum": 2, "q_ja": "その母親は赤ちゃんにとても----。", "a_ja": ["誕生", "優しい", "支配", "国内の"]},
    "I like to ----- in a hot bath.": {"anum": 2, "q_ja": "私は熱いお風呂で----するのが好きだ。", "a_ja": ["満足させる", "リラックスする", "扱う", "感謝する"]},
    "John ----- behind the door until everyone had gone.": {"anum": 3, "q_ja": "ジョンは皆が行ってしまうまでドアの後ろに----ていた。", "a_ja": ["保存する", "抗議する", "隠れる(hid)", "維持する"]},
    "The word \"affluent\" is ----- to \"rich\" in meaning.": {"anum": 4, "q_ja": "「affluent」という単語は意味において「rich」に----。", "a_ja": ["～かなと思う", "影響する", "微細な", "近い"]},
    "Destruction of ----- is a serious problem.": {"anum": 3, "q_ja": "----の破壊は深刻な問題だ。", "a_ja": ["救助", "国内の", "自然", "基本的な"]},
    "Some animals have good night -----.": {"anum": 1, "q_ja": "いくつかの動物は夜間の----が良い。", "a_ja": ["視力", "敏感な", "ため息", "神経質な"]},
    "We walked along the ----- and watched the sunset.": {"anum": 2, "q_ja": "私たちは----沿いを歩き、日没を見た。", "a_ja": ["警備員", "海岸", "波", "大洋"]},
    "I am willing to ----- your kind invitation.": {"anum": 4, "q_ja": "喜んであなたの親切な招待を----します。", "a_ja": ["確認する", "許す", "扱う", "受け入れる"]},
    "The group is giving financial ----- to the refugees.": {"anum": 1, "q_ja": "そのグループは難民に財政的----を与えている。", "a_ja": ["援助", "費用", "警備員", "抗議"]},
    "Police have found a vital ----- to the case at last.": {"anum": 3, "q_ja": "警察はついにその事件の極めて重要な----を見つけた。", "a_ja": ["捜索", "冗談", "手がかり", "基本的な"]},
    "At the summit, a wooden sign gave the altitude as 3,192 ----- above sea level.": {"anum": 3, "q_ja": "山頂で、木の看板が海抜3,192----という高度を示していた。", "a_ja": ["マイル", "キロメートル", "メートル", "実に"]},
    "It is ----- for us to talk over this matter.": {"anum": 3, "q_ja": "私たちがこの問題について話し合うことは----だ。", "a_ja": ["歓呼", "捜索された", "必要な", "費用"]},
    "I remember seeing her ----- in Rome.": {"anum": 2, "q_ja": "私はローマの----で彼女に会ったのを覚えている。", "a_ja": ["どこでも", "どこかで", "どこでも", "中心"]},
    "London is one of the world's leading ----- of financial services.": {"anum": 2, "q_ja": "ロンドンは金融サービスの世界的----の一つだ。", "a_ja": ["会社", "中心", "底", "真ん中"]},
    "I felt ill at the ----- of blood.": {"anum": 3, "q_ja": "私は血を----て気分が悪くなった。", "a_ja": ["原因", "瞬間", "光景", "重さ"]},
    "He ----- for his trip by packing his clothes.": {"anum": 3, "q_ja": "彼は服を詰めて旅行の----をした。", "a_ja": ["着く", "やめる", "準備する", "捜索する"]},
    "Exercise has become part of my ----- routine.": {"anum": 1, "q_ja": "運動は私の----の日課の一部になった。", "a_ja": ["毎日の", "神秘", "行い", "普遍的な"]},
    "A lot of people ----- the party.": {"anum": 2, "q_ja": "多くの人々がパーティーに----した。", "a_ja": ["貿易した", "出席した", "所属した", "混ぜた"]},
    "Do you know the  ----- meaning of this word?": {"anum": 1, "q_ja": "この単語の----の意味を知っていますか？", "a_ja": ["本来の", "安い", "生の", "裸の"]},
    "It ----- us 20,000 dollars to advertise in the newspaper.": {"anum": 3, "q_ja": "新聞に広告を出すのに2万ドル----。", "a_ja": ["出席した", "混ぜた", "（費用が）かかる", "貿易した"]},
    "Some people say that Tahiti is ----- on earth.": {"anum": 3, "q_ja": "タヒチは地上の----だと言う人もいる。", "a_ja": ["瞬間", "前方へ", "天国、楽園", "次の"]},
    "The two countries have ----- friendly relations.": {"anum": 3, "q_ja": "その二国は友好関係を----している。", "a_ja": ["救助した", "存在した", "維持した", "生き残った"]},
    "He tried to think of a clever ----- for his English essay.": {"anum": 3, "q_ja": "彼は英語のエッセイのために気の利いた----を考えようとした。", "a_ja": ["誕生", "販売", "題名", "生の"]},
    "Sit ----- you like.": {"anum": 3, "q_ja": "----好きなところに座りなさい。", "a_ja": ["正確に", "どこにも～ない", "どこでも", "ほとんど"]},
    "The ----- owner of this house is still alive.": {"anum": 2, "q_ja": "この家の----の持ち主はまだ生きている。", "a_ja": ["前方へ", "以前の", "さらなる", "扱い"]},
    "Plants ----- nutrients from the soil.": {"anum": 2, "q_ja": "植物は土壌から栄養分を----する。", "a_ja": ["いたずら", "吸収する", "頼る", "所属する"]},
    "The school was ----- because of COVID-19.": {"anum": 3, "q_ja": "学校はCOVID-19のために----された。", "a_ja": ["近い", "密接に", "閉鎖された", "閉鎖すること"]},
    "She was ----- about the examination.": {"anum": 3, "q_ja": "彼女は試験について----になっていた。", "a_ja": ["吊るした", "価値", "神経質な", "準備された"]},
    "It was ----- of me to make such a mistake.": {"anum": 1, "q_ja": "そんな間違いをするなんて私は----だった。", "a_ja": ["愚かな", "基本的な", "いつもの", "勇敢な"]},
    "He wrote a book about his jungle -----.": {"anum": 2, "q_ja": "彼はジャングルでの----についての本を書いた。", "a_ja": ["裸の", "冒険", "封筒", "誕生"]},
    "My sister gave ----- to twins last month.": {"anum": 4, "q_ja": "私の姉は先月双子を----した。", "a_ja": ["独創的な", "起源", "根", "誕生"]},
    "That ----- book on the shelf is a dictionary.": {"anum": 1, "q_ja": "棚にあるあの----い本は辞書だ。", "a_ja": ["厚い", "太った", "高さ", "重さ"]},
    "Decisions were made on the basis of incorrect -----.": {"anum": 2, "q_ja": "決定は不正確な----に基づいて下された。", "a_ja": ["封筒", "情報", "価値", "中心"]},
    "This house was built in the ----- of the 20th century.": {"anum": 1, "q_ja": "この家は20世紀----に建てられた。", "a_ja": ["真ん中", "どこかで", "どこでも", "中心"]},
    "He is proud of his father being a ----- police officer.": {"anum": 4, "q_ja": "彼は父親が----な警察官であることを誇りに思っている。", "a_ja": ["尊敬", "正直な", "愚かな", "勇敢な"]},
    "The ship weighs 5,000 -----.": {"anum": 3, "q_ja": "「その船の重さは5,000----だ。」", "a_ja": ["ダース", "セント", "トン", "メートル"]},
    "She ----- his voice on the phone.": {"anum": 2, "q_ja": "彼女は電話で彼の声だと----った。", "a_ja": ["扱った", "認識した、わかった", "口論した", "許した"]},
    "They ----- for a cure for the disease.": {"anum": 1, "q_ja": "彼らはその病気の治療法を----した。", "a_ja": ["探した", "ため息をついた", "やめた", "着いた"]},
    "Mr. Carnegie ----- me a good job.": {"anum": 1, "q_ja": "カーネギー氏は私に良い仕事を----た。", "a_ja": ["申し出た", "称賛した", "歓呼した", "頼った"]},
    "She ----- her hand at me in welcome.": {"anum": 2, "q_ja": "彼女は歓迎して私に手を----った。", "a_ja": ["保護した", "振った", "呼吸した", "隠れた"]},
    "The waves on the ----- are high today.": {"anum": 3, "q_ja": "今日は----の波が高い。", "a_ja": ["底", "どこでも", "大洋、海", "洞窟"]},
    "He'll be with us in a few -----.": {"anum": 3, "q_ja": "彼は数----で私たちと合流するだろう。", "a_ja": ["実に", "メートル", "分", "後者の"]},
    "One of the eggs ----- off the edge of the counter.": {"anum": 1, "q_ja": "卵の一つがカウンターの端から----落ちた。", "a_ja": ["転がった", "所属した", "頼った", "飛び込んだ"]},
    "You should ----- smoking.": {"anum": 4, "q_ja": "あなたは喫煙を----すべきだ。", "a_ja": ["許す", "愚かな", "飲み込む", "やめる"]},
    "None of them ----- the war.": {"anum": 1, "q_ja": "彼らの誰も戦争を----なかった。", "a_ja": ["生き残った", "援助した", "存在した", "救助した"]},
    "He brushed ----- off his clothes.": {"anum": 3, "q_ja": "彼は服から----を払い落とした。", "a_ja": ["洞窟", "海岸", "砂", "波"]},
    "We must pick ----- for our research papers by next week.": {"anum": 2, "q_ja": "私たちは来週までに研究論文の----を選ばなければならない。", "a_ja": ["会社", "トピック", "価格", "コピー"]},
    "I could never ----- her for what she had done.": {"anum": 4, "q_ja": "彼女がしたことについて、私は決して彼女を----すことができなかった。", "a_ja": ["貿易する", "吸収する", "探す", "許す"]},
    "After installing the program, just start your computer in the ----- way.": {"anum": 1, "q_ja": "プログラムをインストールした後、----の方法でコンピュータを起動してください。", "a_ja": ["通常の", "援助", "支配", "保護する"]},
    "I suppose he's coming, but I'm not ----- sure.": {"anum": 3, "q_ja": "彼は来ると思うが、----確信しているわけではない。", "a_ja": ["近い", "微細な", "全く", "ほとんど"]},
    "He got ----- to my sister.": {"anum": 2, "q_ja": "彼は私の姉と----した。", "a_ja": ["所属した", "結婚した", "冗談", "吸収された"]},
    "Are there any ----- restaurants around here?": {"anum": 3, "q_ja": "この辺りに----いレストランはありますか？", "a_ja": ["価格", "費用", "安い", "価値"]},
    "The nearest town is 30 ----- away.": {"anum": 4, "q_ja": "一番近い町は30----離れている。", "a_ja": ["分", "トン", "セント", "キロメートル"]},
    "Cows and sheep eat -----.": {"anum": 4, "q_ja": "牛や羊は----を食べる。", "a_ja": ["洞窟", "泥", "砂", "草"]},
    "On hearing the news, she ----- with relief.": {"anum": 3, "q_ja": "その知らせを聞いて、彼女は安堵の----をついた。", "a_ja": ["準備した", "神経質な", "ため息をついた", "優しい"]},
    "You turn this dial to ----- the central heating.": {"anum": 1, "q_ja": "セントラルヒーティングを----するにはこのダイヤルを回します。", "a_ja": ["調節する、支配する", "導く", "普遍的な", "必要な"]},
    "You will get ----- by complaining like that.": {"anum": 2, "q_ja": "そんな風に文句を言っても----（どこへもたどり着かない）。", "a_ja": ["どこでも", "どこへも～ない", "いつでも", "どんなに～でも"]},
    "A ----- is always at the entrance of this building.": {"anum": 4, "q_ja": "この建物の入り口にはいつも----がいる。", "a_ja": ["援助", "抗議", "救助", "警備員"]},
    "Don't be troubled with ----- differences.": {"anum": 2, "q_ja": "----な違いに悩まされるな。", "a_ja": ["薄い", "密接に", "微細な", "近い"]},
    "I'll call the hotel and ----- our reservations.": {"anum": 2, "q_ja": "ホテルに電話して予約を----します。", "a_ja": ["感謝する", "確認する", "受け入れる", "調和する"]},
    "Everybody is aware that smoking ----- health.": {"anum": 1, "q_ja": "喫煙が健康に----することは誰もが知っている。", "a_ja": ["影響する", "確認する", "引き起こす", "反応する"]},
    "I don't know what is in this can because it has no -----.": {"anum": 1, "q_ja": "----がないので、この缶に何が入っているかわからない。", "a_ja": ["ラベル", "独創的な", "謎", "起源"]},
    "Happiness is a topic of ----- interest.": {"anum": 4, "q_ja": "幸福は----な関心事のトピックだ。", "a_ja": ["申し出る", "挨拶する", "称賛する", "普遍的な"]},
    "This car can do 150 ----- per hour.": {"anum": 2, "q_ja": "この車は時速150----出せる。", "a_ja": ["分", "マイル", "ほとんど", "トン"]},
    "Our job is to ----- tropical rain forests.": {"anum": 4, "q_ja": "私たちの仕事は熱帯雨林を----することだ。", "a_ja": ["抗議する", "呼吸する", "生き残る", "保存する、保護する"]},
    "I bought this shirt on -----.": {"anum": 1, "q_ja": "私はこのシャツを----で買った。", "a_ja": ["セール", "価値", "安い", "費用"]},
    "The ----- is inhabited by bats.": {"anum": 3, "q_ja": "その----にはコウモリが住んでいる。", "a_ja": ["砂", "草", "洞窟", "大洋"]},
    "Oil ----- are certain to rise following the agreement to limit production.": {"anum": 2, "q_ja": "生産制限の合意を受けて、石油----は確実に上昇するだろう。", "a_ja": ["必要な", "価格", "高価な", "会社"]},
    "He surprised us by saying that he was leaving the -----.": {"anum": 3, "q_ja": "彼は----を辞めると言って私たちを驚かせた。", "a_ja": ["価値", "自然", "会社", "新聞"]},
    "He was sick in the evening, but the ----- day he was better.": {"anum": 2, "q_ja": "彼は夕方気分が悪かったが、----日は良くなっていた。", "a_ja": ["さらなる", "次の", "中心の", "前方へ"]},
    "The plane took off at ----- 9:00 a.m.": {"anum": 1, "q_ja": "飛行機は午前9時----に離陸した。", "a_ja": ["正確に", "かなり", "正確な", "全く"]},
    "She put the letter in an -----.": {"anum": 3, "q_ja": "彼女は手紙を----に入れた。", "a_ja": ["情報", "ラベル", "封筒", "コピー"]},
    "This dance has its ----- in Okinawa.": {"anum": 2, "q_ja": "この踊りは沖縄に----がある。", "a_ja": ["真ん中", "起源", "生の", "中心"]},
    "We ----- our son to use the family car.": {"anum": 2, "q_ja": "私たちは息子が家の車を使うことを----した。", "a_ja": ["確認した", "許可した", "認識した", "調和した"]},
    "I'll ----- you to the meeting room.": {"anum": 4, "q_ja": "会議室へご----します。", "a_ja": ["申し出る", "許す", "飛び込む", "案内する、導く"]},
    "They had a ----- over the problem.": {"anum": 4, "q_ja": "彼らはその問題について----した。", "a_ja": ["試合", "競争", "光景", "口論"]},
    "I'll go ----- you want.": {"anum": 1, "q_ja": "あなたが望むところなら----へでも行きます。", "a_ja": ["どこでも", "全く", "かなり", "どんなに～でも"]},
    "The hall is ----- full.": {"anum": 3, "q_ja": "ホールは----満員だ。", "a_ja": ["満足した", "閉じた", "ほとんど", "維持した"]},
    "She was born in the ----- half of the 18th century.": {"anum": 2, "q_ja": "彼女は18世紀----に生まれた。", "a_ja": ["前方へ", "中心の", "後半の", "さらなる"]},
    "The signal for a ----- to start is often the firing of a gun.": {"anum": 4, "q_ja": "----開始の合図はしばしば銃の発砲だ。", "a_ja": ["扱い", "天国", "口論", "レース"]},
    "I ----- my jacket on a nail.": {"anum": 4, "q_ja": "私は釘でジャケットを----ってしまった。", "a_ja": ["巻いた", "引き起こした", "閉じた", "破った"]},
    "He leaves his office door open, ----- cold it is.": {"anum": 2, "q_ja": "----寒くても、彼はオフィスのドアを開けたままにしている。", "a_ja": ["正確に", "どんなに～でも", "いつでも", "どこでも"]},
    "The company is moving to new offices in ----- London.": {"anum": 2, "q_ja": "その会社はロンドン----の新しいオフィスに移転する。", "a_ja": ["後半の", "中心の", "さらなる", "前方へ"]},
    "Thousands of people ----- against discrimination.": {"anum": 3, "q_ja": "何千もの人々が差別に対して----した。", "a_ja": ["救助した", "逃げた", "抗議した", "隠れた"]},
    "A loud ----- rose from the fans in the stadium.": {"anum": 4, "q_ja": "スタジアムのファンから大きな----が上がった。", "a_ja": ["神秘", "挨拶する", "勇敢な", "歓声"]},
    "What is a ----- English breakfast?": {"anum": 4, "q_ja": "----なイギリスの朝食とはどのようなものですか？", "a_ja": ["正直な", "冒険", "独創的な", "典型的な"]},
    "They ----- for relics on the bottom of the sea.": {"anum": 4, "q_ja": "彼らは海底の遺物を探して----った。", "a_ja": ["行う", "許す", "納得させる", "潜る"]},
    "The beetle is about fifteen ----- long.": {"anum": 4, "q_ja": "そのカブトムシは約15----の長さだ。", "a_ja": ["トン", "センチメートル", "マイル", "メートル"]},
    "Imagination is ----- to the human mind.": {"anum": 3, "q_ja": "想像力は人間の精神にとって----（不可欠）なものだ。", "a_ja": ["導く", "頼る", "基本的な", "支配する"]},
    "His right leg was ----- with a bandage.": {"anum": 1, "q_ja": "彼の右足は包帯で----かれていた。", "a_ja": ["巻かれた", "破られた", "満足した", "閉じられた"]},
    "Which direction is the ----- blowing from?": {"anum": 4, "q_ja": "----はどの方角から吹いていますか？", "a_ja": ["涙", "驚き", "瞬間", "風"]},
    "Whales ----- to mammals.": {"anum": 4, "q_ja": "クジラは哺乳類に----する。", "a_ja": ["混ぜる", "頼る", "存在する", "属する"]},
    "The teacher was ----- with the students' progress.": {"anum": 2, "q_ja": "先生は生徒たちの進歩に----していた。", "a_ja": ["反応した", "満足した", "～かなと思った", "驚いた"]},
    "The runner was ----- hard after training.": {"anum": 3, "q_ja": "そのランナーはトレーニングの後、激しく----していた。", "a_ja": ["逃げている", "隠れている", "呼吸している", "援助している"]},
    "Don't ----- me like a child.": {"anum": 2, "q_ja": "私を子供のように----わないで。", "a_ja": ["調和する", "扱う", "レース", "許す"]},
    "I'll meet you at the ----- time.": {"anum": 2, "q_ja": "----の時間に会いましょう。", "a_ja": ["典型的な", "いつもの", "毎日の", "申し出"]},
    "America is increasing ----- with Asian countries.": {"anum": 2, "q_ja": "アメリカはアジア諸国との----を増やしている。", "a_ja": ["援助", "貿易", "価格", "販売"]},
    "They ----- from the burning building.": {"anum": 1, "q_ja": "彼らは燃えている建物から----た。", "a_ja": ["逃げた", "救助した", "保護した", "隠れた"]},
    "May I have two ----- of these pencils?": {"anum": 4, "q_ja": "この鉛筆を2----いただけますか？", "a_ja": ["セント", "トン", "パーセント", "ダース"]},
    "We were ----- at the result.": {"anum": 4, "q_ja": "私たちはその結果に----いた。", "a_ja": ["満足させる", "驚くべき", "満足した", "驚いた"]},
    "Of the two plans, I prefer the ----- one.": {"anum": 3, "q_ja": "2つの計画のうち、私は----の方が好きだ。", "a_ja": ["次の", "前方へ", "前者の", "以前の"]},
    "I regretted having played so many ----- on my teacher.": {"anum": 4, "q_ja": "私は先生にたくさんの----をしたことを後悔した。", "a_ja": ["手がかり", "神秘", "冗談", "いたずら"]},
    "I'm tired and can't walk any -----.": {"anum": 4, "q_ja": "私は疲れていて、これ以上----へは歩けない。", "a_ja": ["前者の", "後者の", "中心の", "さらに遠くへ"]},
    "The ----- of the snow broke the branch.": {"anum": 4, "q_ja": "雪の----みで枝が折れた。", "a_ja": ["太った", "厚い", "光景", "重さ"]},
    "I ----- him as a great scientist.": {"anum": 4, "q_ja": "私は彼を偉大な科学者として----している。", "a_ja": ["正直な", "費用", "吸収する", "尊敬する"]},
    "I ----- blue paint with white to make the color of the sky.": {"anum": 1, "q_ja": "私は空の色を作るために青い絵の具を白と----た。", "a_ja": ["混ぜた", "出席した", "保存した", "維持した"]},
    "She still ----- on her parents for money.": {"anum": 3, "q_ja": "彼女はまだ金銭面で両親に----っている。", "a_ja": ["申し出る", "（費用が）かかる", "頼る", "出席する"]},
    "He believes in -----.": {"anum": 4, "q_ja": "彼は----を信じている。", "a_ja": ["厚い", "太った", "薄い", "神"]},
    "We took a ----- flight from Chicago to New York.": {"anum": 3, "q_ja": "私たちはシカゴからニューヨークへの----便に乗った。", "a_ja": ["基本的な", "高価な", "国内の", "普遍的な"]},
    "\"She is a good singer.\"  \"Yes, -----.\"": {"anum": 4, "q_ja": "「彼女は歌が上手だね。」「ああ、----。」", "a_ja": ["ほとんど", "しかしながら", "かなり", "実に、全く"]},
    "An ----- man would never do such a thing.": {"anum": 4, "q_ja": "----な人は決してそんなことはしないだろう。", "a_ja": ["敏感な", "愚かな", "勇敢な", "正直な"]},
    "This pot is of great -----.": {"anum": 2, "q_ja": "この壺は大変な----がある。", "a_ja": ["貿易", "価値", "高価な", "販売"]},
    "He tried to ----- me that he was innocent.": {"anum": 4, "q_ja": "彼は自分が無実であることを私に----させようとした。", "a_ja": ["援助", "題名", "吊るす", "納得させる"]},
    "We learn much of our ----- knowledge at schools.": {"anum": 3, "q_ja": "私たちは学校で----知識の多くを学ぶ。", "a_ja": ["吸収する", "裸の", "基礎的な", "価値"]},
    "Eating ----- carrots is good for your eyesight.": {"anum": 2, "q_ja": "----のニンジンを食べることは視力に良い。", "a_ja": ["根", "生の", "敏感な", "裸の"]},
    "About 65 ----- of our body is water.": {"anum": 3, "q_ja": "私たちの体の約65----は水だ。", "a_ja": ["実に", "トン", "パーセント", "セント"]},
    "These creatures live at the sea -----.": {"anum": 2, "q_ja": "これらの生物は海----に住んでいる。", "a_ja": ["海岸", "底", "大洋", "砂"]},
    "I like baseball ----- than soccer.": {"anum": 1, "q_ja": "私はサッカーよりも----野球が好きだ。", "a_ja": ["むしろ", "実に", "ほとんど", "全く"]},
    "In the summer we wear ----- clothing.": {"anum": 4, "q_ja": "夏には私たちは----着をする。", "a_ja": ["光景", "重さ", "太った", "薄い"]},
    "----- I smiled, he smiled back.": {"anum": 4, "q_ja": "私が微笑むと----、彼は微笑み返した。", "a_ja": ["どこにも～ない", "どこでも", "どんなに～でも", "～するときはいつでも"]},
    "During the summer I worked delivering -----.": {"anum": 2, "q_ja": "夏の間、私は----配達の仕事をした。", "a_ja": ["トピック", "新聞", "冒険", "封筒"]},
    "Gospel has its ----- in African-American religious music.": {"anum": 3, "q_ja": "ゴスペルはアフリカ系アメリカ人の宗教音楽にその----を持つ。", "a_ja": ["独創的な", "コピー", "ルーツ、根", "題名"]},
    "I felt the warm sun on my ----- arms.": {"anum": 1, "q_ja": "私は----の腕に暖かい日差しを感じた。", "a_ja": ["裸の、むき出しの", "底", "独創的な", "高価な"]},
    "Does life ----- on Mars?": {"anum": 2, "q_ja": "火星に生命は----するか？", "a_ja": ["維持する", "存在する", "援助する", "警備する"]},
    "He ----- a yellow-and-red capsule after supper.": {"anum": 4, "q_ja": "彼は夕食後に黄色と赤のカプセルを----んだ。", "a_ja": ["吸収した", "探した", "転がった", "飲み込んだ"]},
    "Call me when you ----- London.": {"anum": 2, "q_ja": "ロンドンに----たら電話して。", "a_ja": ["導く", "着く", "吊るす", "行う"]},
    "Changing the course of the river ----- many problems.": {"anum": 1, "q_ja": "川の流れを変えることは多くの問題を----した。", "a_ja": ["引き起こした", "反応した", "認識した", "扱った"]},
    "The car splashed ----- all over us.": {"anum": 2, "q_ja": "車が私たちに----を跳ねかけた。", "a_ja": ["草", "泥", "大洋", "どこかで"]},
    "How the universe was created still remains a -----.": {"anum": 2, "q_ja": "宇宙がどのように創造されたかは依然として----のままだ。", "a_ja": ["いたずら", "謎、神秘", "冒険", "手がかり"]},
    "He didn't ask for a ----- in return for his help.": {"anum": 2, "q_ja": "彼は手助けのお返しに1----も求めなかった。", "a_ja": ["メートル", "セント", "ダース", "トン"]},
    "An audience usually ----- readily to a good lecturer.": {"anum": 4, "q_ja": "聴衆は通常、良い講演者にはすぐに----する。", "a_ja": ["満足させる", "受け入れる", "認識する", "反応する"]},
    "I made three ----- of my report.": {"anum": 4, "q_ja": "私はレポートの----を3部とった。", "a_ja": ["販売", "根", "洞窟", "コピー"]},
    "She ----- me with a smile.": {"anum": 3, "q_ja": "彼女は笑顔で私に----した。", "a_ja": ["納得させた", "吸収した", "挨拶した", "申し出た"]},
    "We'll ----- the picture on that wall.": {"anum": 1, "q_ja": "私たちはその壁に絵を----けるつもりだ。", "a_ja": ["掛ける", "必要な", "納得させる", "支配する"]},
    "What's the ----- of the pyramid?": {"anum": 3, "q_ja": "そのピラミッドの----はどれくらいですか？", "a_ja": ["重さがある", "光景", "高さ", "高い"]},
}

process_file('901~1050.csv', data)
